### PR TITLE
Explains how to use the player to play a game

### PR DESCRIPTION
**Pull request by Uladox**
Explains how to use the player to run a game in the README in the way most people probably want to know how to without hassle.

### CODE REVIEW

**Comment by carstene1ns** [comment]
It is not really needed to put the Player executable in the game folder, you can even start it from another folder, the working directory matters.

**Comment by Ghabry** [comment]
Or use "--project-path".
A file browser is planned for a later release.

**Comment by carstene1ns** [comment]
Well, command line options are more or less "advanced" usage... :grinning:

**Comment by Ghabry** [comment]
The simplest solution is probably to associate *.ldb files with the Player, then you can run games by double clicking the RPG_RT.ldb flle ^^

**Comment by carstene1ns** [comment]
We could even add a windows-only installer (like NSIS or InnoSetup or the likes), that does it by default for releases.

**Comment by Uladox** [comment]
I think anything is good, but I found it a bit difficult to figure out how to use the player when I first found the project (should I give it a file as an argument was a question that came up). Eventually I stumbled on an old forum link that did it like this. I had been using it like this since (but won't anymore), and reading the README some more I realized this commit is actually pointless. I should have figured that out. I had a bit of trouble figuring out the behavior since I hadn't used the original rpgmaker 2000, and with xmonad several programs behave oddly (although I did manage to get it working by running xmonad with xfce). I guess I have 20/20 hindsight, but blurry foresight  :bowtie:.

**Comment by carstene1ns** [comment]
I am going to implement this helper script in EasyRPG/Tools#18.
Also, there already is a "Running EasyRPG Player" section in the `README`, so this can be closed.

**Comment by fdelapena** [comment]
> Also, there already is a "Running EasyRPG Player" section in the README, so this can be closed.

Indeed, it says already mostly the same:

> Running EasyRPG Player
> ----------------------
>
> Run the easyrpg-player executable from a RPG Maker 2000 or 2003 game
> project folder (same place as RPG_RT.exe).

**Pull request closed without merging**
