### PR TITLE
Android : explanation on how to use the app

### PR DESCRIPTION
**Pull request by BlisterBoy**
#512 
- Clearer message of "no games found"
- New menu item showing a tip on how to use the app
- Displaying this tips in the app's first launch

### CODE REVIEW

**Comment by BlisterBoy** [comment]
Hi guys :), I think this pull request is finished !
The code is now clearer for now developers !

**Comment by fdelapena** [comment]
Thanks! I'll test on multiple devices and emulator images today.

**Comment by BlisterBoy** [comment]
#512 
I finally remade GameBrowser :p.
There is no more onLongClick behavior, a button is at the right of a game to change the region.

Oh, and it's now possible to pimp the item list ^^.

**Comment by BlisterBoy** [comment]
Hi guys :).
I did the @Ghabry suggestion : now there is an activity for API >= 12 and API < 12.
The code is now closer to the MVC pattern.
For the moment, legacy and new activity are identical, but when I'll get time I'll add some API 12 features (action bar functionality, landscape/portrait mode etc.).

**Comment by BlisterBoy** [comment]
Hmmm it seems Jenkins has reject thoses push, but no explanation. Everything's fine for me.

**Comment by fdelapena** [comment]
I'm rebuilding the emscripten toolchain, player-js-pr is failing. Though it is unrelated with this pull request, it shows some checks failed because it launches multiple jobs, including player-android. I'm still trying to fix existing issues with the toolchain. After this I'll prepare a manual pull request for android.

**Comment by BlisterBoy** [comment]
Okay ! Bon courage !

**Comment by BlisterBoy** [comment]
There is now a "refresh" button. Design is slightly better with borderless button.

**Comment by BlisterBoy** [comment]
Hi guys ! I think this is all for a moment, I'll take a break far away from IT universe for some weeks. This pull request is a pretty big one but the code should be ok ! Of course if you find a problem I'll be there to solve it !

**Comment by fdelapena** [comment]
Thank you BlisterBoy, have a nice summer break!

**Pull request merged**
