### PR TITLE
Enable sound on standalone game

### PR DESCRIPTION
**Pull request by carlsonsantana**
This change load settings on standalone games and consequently enable the sound of these apps.

### CODE REVIEW

**Comment by fdelapena** [comment]
jenkins CI: ok to test

**Comment by fdelapena** [comment]
jenkins: ok to test

**Review by fdelapena — APPROVED** [review]
Thank you for the patch! (and for your [convert_rpggame_to_android](https://github.com/carlsonsantana/convert_rpggame_to_android) script! Standalone game improvements for reading from apk/obb without initial extraction are coming soon)

**Review by fmatthew5876 — APPROVED** [review]

**Review by carstene1ns — APPROVED** [review]

**Comment by carstene1ns** [comment]
The actual problem lies here, because SettingsManager is not initialized:
https://github.com/EasyRPG/Player/blob/1fd6e7412cabdfa497574c56b6a075b0e04bf01c/builds/android/app/src/main/java/org/easyrpg/player/game_browser/GameBrowserHelper.java#L255-L257

Maybe we should revert the logic anyway.

**Comment by Ghabry** [comment]
the entire SettingManager is a code-smell anyway. Should be a class instead than this would simply crash with a NullPointerException instead of using default data... (also no idea why there are no sane defaults).

**Pull request merged**
