### PR TITLE
Always draw event sprites, even for tile_id = 0

### PR DESCRIPTION
**Pull request by scurest**
This fixes the first part of #1169, with the invisible event. I'm PRing it separately because this one should be much easier to review than the fix for the second part.

### CODE REVIEW

**Comment by Ghabry** [comment]
Made some tests with the editor to see how actor_id and character_name are populated and I think a condition on character_name is the correct behaviour. Just funny that it took so long to find a game that breaks due to this :D. Everybody using 0 as transparent tile it seems.

**Comment by Ghabry** [comment]
@scurest 
I found a regression: When the event has no runnable page (no page that fulfills the start condition) then the event is really invisible instead of showing tile 0 :)

**Comment by scurest** [comment]
ლ(` Д ´  )ლ

We should probably just not draw those at all. How about something like this?

    diff --git a/src/game_event.cpp b/src/game_event.cpp
    index cad9e7e5..5bed38ac 100644
    --- a/src/game_event.cpp
    +++ b/src/game_event.cpp
    @@ -345,10 +345,12 @@ void Game_Event::Refresh() {
     		// Loop in reverse order to see whether any page meets conditions...
     		if (AreConditionsMet(*i)) {
     			new_page = &(*i);
    +			SetVisible(true);
     			// Stop looking for more...
     			break;
     		}
     	}
    +	if (!new_page) SetVisible(false);
     
     	// Only update the page pointer when game is loaded,
     	// don't setup event, already done

**Comment by Ghabry** [comment]
Can confirm that this fixes the regression. Will append this to my PR

**Pull request merged**
