### PR TITLE
Android : Allow ghost mode

### PR DESCRIPTION
**Pull request by BlisterBoy**
Hi everyone
This PR add a "Ghost" button. It's basically a "Ctrl" button combined with the --test-play flag.
We already discussed about it in the IRC Channel but let's remind the reasons why I implemented this : 

+ It permits to pass through some Player problems, in my case I'm able to bypass #687 and continue my game.
+ Without considering the Player, there is a lot of RPG Maker games where this features is useful (a bug left by the maker, a pnj blocking your way etc. etc.). I used to play through the RPG Maker Editor to use the ctrl button after too many stuck situations.
+ The option is not too obvious in the settings

- This could be saw as "cheating", but hey it's just gaming and it brings way more positive than negative.

NB : This PR is based on #708 so please don't merge it before merging the other PR.
NB2 : There is a bug in #708 related to the --encoding flag for the moment, if you want to test it, comment this flag in GameBrowserHelper.java

### CODE REVIEW

**Comment by Ghabry** [comment]
You can already ghost with SHIFT, also in RPG_RT

**Comment by Ghabry** [comment]
And this is hard to Review because you included tons of commits from me which are listed in the diff. Why?
Please read about git rebase.

**Comment by BlisterBoy** [comment]
Oô ?
Shift is a key used by many 2k3 games, are you sure ?

**Comment by Ghabry** [comment]
Ah okay you based it on my branch. This explains the strange commit log. Nevermind.

You are right. It's LeftCtrl and you just expose it to Android. Now I get it :D

**Comment by Ghabry** [comment]
Btw you can fast forward messages in TestPlay mode (you call it GhostMode) via LeftShift.

**Comment by BlisterBoy** [comment]
Ah nice !

**Comment by BlisterBoy** [comment]
Oh yes I'm on your branch because you add a lot of stuff and I use some of them. I'll switch to mine after the merge of #708 :p

**Comment by carstene1ns** [comment]
yo, mr. jenkins: test this please!

**Comment by carstene1ns** [comment]
hello mr jenkins, how you doin'? please test this²

**Comment by carstene1ns** [comment]
oh come on, test this please :+1:

**Comment by fdelapena** [comment]
IMO this options should be hidden by default. Also, forcing `--test-play` for all games by default might bring false positive reports, i.e. force skipping messages (TestPlay feature) might misbehave in some cutscenes, making forced message skipping end before a timed cutscene playing with "continuing events" run out of sync.

Instead of forcing `--test-play` for all games I think it should be added for every game, by adding to the RPG_RT.ini:
```ini
    [EasyRPG]
    TestPlay=1
```
Then, when player detects this feature, add new options to button preset, such ctrl, F9, force call save, etc., otherwise keeping them hidden for end users to prevent easy cheats which might bring bad reports such "game hangs after cheating a bit here and there".

**Comment by Ghabry** [comment]
But please don't write code for Android that writes in RPG_RT.ini anymore. Only easyrpg-prefs will be writable when the game directory is on a read-only storage.

For Android probably a new game Setting via easyrpg-prefs.txt

**Comment by Ghabry** [comment]
Another way: Add a global option "Add cheats to game menu" and when it's touched show a msgbox that explains about "Adding cheat button to Ui" and "Toggle it via game menu". to the settings and when this option is on you get a new item in the "back-menu" (where you can toggle FPS and buttons) called "Enable/Disable cheats" which does a JNI call to toggle Player::debug_flag (see the Player::exit_flag one on "End Game" for an example)

**Comment by BlisterBoy** [comment]
I was thinking of a system like that Ghabry. But you have to keep in mind that it make the code and the UI more complicated and harder to understand.
There is another solution (automatic enabling of debug_flag if the button mapping system contains a ghost mode button), but it can cost system call depending of how I'll implemented it.

Did one of you have tested the actual system ? @fdelapena  it's already pretty hidden (you have to scroll at maximum to see the button), it doesn't permit show F9 buttons, just Ghost Mode, and if I understood, --test-play flag doesn't change anything until the player stay pressed with the Ghost Mode button (people won't find bug that way because they know they're using a debug functionnality).

When I'll have the time today or tomorrow, I'll sumarry different option we have and details the pro & cons I see in theses, you'll choose :). Have a good day guys !

**Comment by Ghabry** [comment]
The debug_flag also skips our branding on game startup :(

**Comment by Ghabry** [comment]
Please rebase the commit list and remove all commits that are not yours. Most of these commits are useless because they are already in upstream. Merge commits are also useless when rebasing and be removed.

```
# if not already done
git remote add upstream https://github.com/EasyRPG/Player.git

git rebase -i upstream/master
```

This opens an editor based on EDITOR environment variable.
Delete all commit lines that are *not yours* or *merge commits*.
Then save the file.

Then verify with git log that only 2 (if I counted correct) commits are left and do a forced push. Hint: Make a backup of your repository before rebasing to prevent data loss if done incorrectly ;)

**Comment by BlisterBoy** [comment]
Thank you Ghabry for the tips.
I think it's the time, I can no longer run away : I have to read the git documenation.

**Comment by BlisterBoy** [comment]
Hi guys, I have too many conflict trying to rebase this.
Considering this worthless (I'll just keep one commit, and change the way the system work), I'm saving times  starting from scratch !

**Pull request closed without merging**
