### PR TITLE
Android: Update to SDL2.0.9

### LINKED ISSUE #1518: Android: Update SDLActivity for SDL 2.0.9
Before releasing 0.6 (likely) we should update SDL2 on Android to the latest Version to fix problems like "crashes on startup" which are not under our control.

### PR DESCRIPTION
**Pull request by Ghabry**
As usual the diff is ugly because of SDL...

Basicly I just patched our stuff into SDLActivity.java as usual and added hidapi-support.

SDL bugfix: On Android < 4.4 the hidapi load must be before SDL load, moved the acquire call up to handle this.

Tested on:
Android 4.1
Android 7.1

Going to send my APK to the one on FB who had crashes.

Compiled APK (uses a different signing key, which means you must uninstall the other app before): https://easyrpg.org/downloads/tmp/EasyRpg209.apk

---

Fixes #1518.

### CODE REVIEW

**Comment by carstene1ns** [comment]
Great, will do a test myself later.

**Comment by carstene1ns** [comment]
Going to push this to the play store beta channel.

**Comment by carstene1ns** [comment]
jenkins: test this please.

**Comment by BlisterB** [comment]
It seems that this update brings a lot of gamepad fixes.
https://www.libsdl.org/tmp/SDL/WhatsNew.txt

I previously tried to implement custom controls for gamepad but faced a lot of bizarre bugs (mostly gamepad not detected after launching a second game), Hopefully it will be better now.

**Pull request merged**
