### PR TITLE
Battle 2k3: Skills + Equip State infliction

### LINKED ISSUE #1490: Abnormal state
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
www.mediafire.com/file/k0969lkmqqax6hu/
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:

Life recovery and mana recovery turns to decrease instead

### PR DESCRIPTION
**Pull request by Ghabry**
the two WIP commits.

Not mergable yet.

Fix #1490

### CODE REVIEW

**Comment by fmatthew5876** [comment]
We should verify what values are in the state chunks when this feature is active. Do they get locked at 1? Some really high number? 0 but still treated as active anyway?

Otherwise it could break save games.

**Comment by Ghabry** [comment]
I already tested the +10 stuff, works like all other AddState cases

**Comment by fmatthew5876** [comment]
If #1726 is adopted as is, this would change. The new paradigm is to call `AddState()` and `RemoveState()` and check the return value if it was successful. In your case it would check for equipment states and return false.

**Comment by Ghabry** [comment]
see matthews battle prs which include this

**Pull request closed without merging**
