### PR TITLE
Optimize Variables and switches + Add Tests

### PR DESCRIPTION
**Pull request by fmatthew5876**
Optimizes switch and variable access for logic heavy games. Also cleanups singletons and adds unit tests.

Master:
```
----------------------------------------------------------
Benchmark                   Time           CPU Iterations
----------------------------------------------------------
BM_SwitchGet                4 ns          4 ns  189047081
BM_SwitchSet                5 ns          5 ns  136290582
BM_SwitchFlip               7 ns          7 ns  103273384
BM_SwitchSetRange        5009 ns       5009 ns     141417
BM_SwitchFlipRange       6717 ns       6717 ns     105261

------------------------------------------------------------
Benchmark                     Time           CPU Iterations
------------------------------------------------------------
BM_VariableGet                3 ns          3 ns  234503273
BM_VariableSet                4 ns          4 ns  166569307
BM_VariableAdd                7 ns          7 ns  102786779
BM_VariableSub                7 ns          7 ns  100826372
BM_VariableMult               7 ns          7 ns  100840661
BM_VariableDiv                9 ns          8 ns   81506066
BM_VariableMod                8 ns          8 ns   82874145
BM_VariableSetRange        4133 ns       4104 ns     170068
BM_VariableAddRange        6829 ns       6783 ns     104131
BM_VariableSubRange        7187 ns       7129 ns     100112
BM_VariableMultRange       7201 ns       7140 ns      97368
BM_VariableDivRange        9557 ns       9480 ns      73299
BM_VariableModRange        8700 ns       8635 ns      79854
```

This PR:
```
----------------------------------------------------------
Benchmark                   Time           CPU Iterations
----------------------------------------------------------
BM_SwitchGet                1 ns          1 ns  493785383
BM_SwitchSet                5 ns          5 ns  136517949
BM_SwitchFlip               5 ns          5 ns  136289613
BM_SwitchSetRange        1282 ns       1282 ns     551636
BM_SwitchFlipRange       1251 ns       1251 ns     547390


-----------------------------------------------------------------------
Benchmark                     Time           CPU Iterations
------------------------------------------------------------
BM_VariableGet                3 ns          3 ns  267765975
BM_VariableSet                4 ns          4 ns  158529616
BM_VariableAdd                4 ns          4 ns  161540747
BM_VariableSub                5 ns          5 ns  150471152
BM_VariableMult               6 ns          6 ns  130454647
BM_VariableDiv                8 ns          8 ns   94011699
BM_VariableMod                6 ns          6 ns  107436757
BM_VariableSetRange         916 ns        916 ns     757338
BM_VariableAddRange         687 ns        687 ns    1026075
BM_VariableSubRange         618 ns        618 ns    1092798
BM_VariableMultRange        687 ns        687 ns    1025344
BM_VariableDivRange        2366 ns       2366 ns     291713
BM_VariableModRange        2354 ns       2352 ns     294594
```

### CODE REVIEW

**Comment by fmatthew5876** [comment]
Here are some improvements in Frozen Triggers.

This profile was taken for 10 seconds at the beginning of the game with the blowing snow.

Master
fzold

This PR
fznew

**Comment by Ghabry** [comment]
Wow this is some significant improvement.
Also that VTune is cool, didn't knew it exists for Linux :o. Looks like the Visual Studio Profiler, now I don't need to boot my Windows VM anymore for this :+1:

**Comment by fmatthew5876** [comment]
Surprisingly looks like `Game_Map::Refresh()` only takes 0.5% of the time in my profile.

**Comment by Ghabry** [comment]
Looks also good to me. Only minor thing I see that the switches have a return value of "int". Is that intentional? Shouldn't have side-effects, just looks strange. xD (but if you plan to change this add this to some other PR, don't create PRs for such one line changes pls, dat queue) ;)

**Comment by fmatthew5876** [comment]
That's a big, has no material effect but should be fixed. Will shove into another pr

**Comment by fmatthew5876** [comment]
> Looks also good to me. Only minor thing I see that the switches have a return value of "int". Is that intentional? Shouldn't have side-effects, just looks strange. xD (but if you plan to change this add this to some other PR, don't create PRs for such one line changes pls, dat queue) ;)

Actually I don't see this. Maybe that was an older version of the code? All the switches Get and Set methods in master are returning bool.

**Comment by Ghabry** [comment]
can confirm, is not in the final product.

**Comment by carstene1ns** [comment]
This one unfortunately has another long vs. int discrepancy in newlib on 3ds:

```c++
/opt/jenkins/workspace/player-3ds/builds/3ds/../../src/game_variables.cpp: At global scope:
/opt/jenkins/workspace/player-3ds/builds/3ds/../../src/game_variables.cpp:64:23: error: no declaration matches 'Game_Variables::Var_t Game_Variables::SetOp(int, Game_Variables::Var_t, F&&, const char*)'
   64 | Game_Variables::Var_t Game_Variables::SetOp(int variable_id, Var_t value, F&& op, const char* warn) {
      |                       ^~~~~~~~~~~~~~
In file included from /opt/jenkins/workspace/player-3ds/builds/3ds/../../src/game_variables.cpp:19:
/opt/jenkins/workspace/player-3ds/builds/3ds/../../src/game_variables.h:72:7: note: candidate is: 'template<class F> int Game_Variables::SetOp(int, Game_Variables::Var_t, F&&, const char*)'
   72 |   int SetOp(int variable_id, Var_t value, F&& op, const char* warn);
      |       ^~~~~
/opt/jenkins/workspace/player-3ds/builds/3ds/../../src/game_variables.h:29:7: note: 'class Game_Variables' defined here
   29 | class Game_Variables {
      |       ^~~~~~~~~~~~~~
In file included from /opt/jenkins/workspace/player-3ds/builds/3ds/../../src/game_variables.h:23,
                 from /opt/jenkins/workspace/player-3ds/builds/3ds/../../src/game_variables.cpp:19:
/opt/jenkins/workspace/player-3ds/builds/3ds/../../src/game_variables.cpp: In instantiation of 'void Game_Variables::SetOpRange(int, int, Game_Variables::Var_t, F&&, const char*) [with F = long int (&)(long int, long int); Game_Variables::Var_t = long int]':
/opt/jenkins/workspace/player-3ds/builds/3ds/../../src/game_variables.cpp:122:79:   required from here
```

**Pull request merged**
