### PR TITLE
Battle animations

### PR DESCRIPTION
**Pull request by scurest**
Implements some missing features for battle animations. In particular

* both the screen and the target (on either the map or in battle) should flash correctly now  
    battler_flash
* battle animations are not fixed to the point on the screen where they first occurred, but follow their targets around  
    follow
* the position of animations targeting map characters is fixed (#365)  
    position
* "Show on entire map" animations work, I think

Shaking isn't implemented, but there's an obvious path to doing it once shaking is actually working :)

What I'm planning to do before I call this finished:

- [x] ~~`Game_Screen::ShowGlobalBattleAnimation` was completely removed. Need to check exactly what RPG_RT does in this case (should be used for targeting the whole enemy party, I think)~~ Done for RM2k3, need to check 2k now
- [x] Need to check I didn't break 809b381

(Also, @Ghabry, I backed out the `GetX`/`SetX`/etc. functions from `BattleAnimation` you just put in. Hope that's okay...)

### CODE REVIEW

**Comment by Ghabry** [comment]
Cool, working battle animations. Seems we need a 0.3.2 hotfix soon.

Yeah, change whatever you want, only the result matters :)

**Comment by BlisterBoy** [comment]
Cool commits guy !
The project is really increasing in quality, it's a shame that I don't have time to get back to C++ !

**Comment by Ghabry** [comment]
Don't worry @BlisterBoy you can help us by improving the Android port by using Java :D

**Comment by BlisterBoy** [comment]
The external storage thing broke my heart hahaha. I don't really know what to do except this one : [, I'm open to any proposition !

**Comment by scurest** [comment]
So, I decided _not_ to fix "Show on entire map animations" on looping maps. The problem is that the animations are located at the vertices of a 20x10(11?) grid which is independent of the map. So after looping around, the animations play at different spots on the map. Illustration: (the white grid shows the map edges, and the red spots are where animations play)

entiremap

So you can't know where to put them just from `GetDisplayX`/`Y` and would have to complicate `Game_Map` with code to track the position against the grid of animations. OTOH, the graphical glitch from this tiny: just a slight jump in the animation grid position when the camera crosses a looping map edge. So I kind of decided it's not worth it.

**Comment by scurest** [comment]
That said, this is ready.

**Comment by Ghabry** [comment]
The same graphical glitch happens with Panoramas at the moment when crossing map boundaries. As you said: Not worth it.

Have no time until Thursday, somebody else can review. (fdela: when 0.3.2 release?)

**Comment by fdelapena** [comment]
Thanks scurest, great fixes and improvements :+1:. Also 2k3 battlers flickering was annoying :smile:.

I have an exam tomorrow, same here until Thursday.

**Comment by Ghabry** [comment]
Okay the flickering was then not observable for me because the VS-compiler probably inserted a 0. Good find.

**Comment by fdelapena** [comment]
It seems like the animation sound playing when attacking is not OK anymore in OFF. The attack sound plays the same as the hit sound. Other things worked like a charm :+1:.

**Comment by scurest** [comment]
My bad. Of course there can be multiple `AnimationTiming` for one frame (eg. flash both the target and screen, though OFF's playing two SEs in one frame doesn't make a lot of sense). Try this.

**Comment by fdelapena** [comment]
Thanks! now it plays the splat audio combined. It seems to behave correctly now.
(I guess it sounds different than RPG_RT because of #349, but this one won't be soon probably).

**Comment by scurest** [comment]
Urk, you're right. I changed it to only play the last SE if there are multiple in one frame... Sorry, one more try.

**Comment by Ghabry** [comment]
I have an empty frame now in rpg2k3 battles when the battler is a battle animation. This wasn't happening before.
My fix to this was "return GetFrame()+1 >= GetFrames();", but you have this code already...

There is one corner case, but I assume almost no game uses this because it's nonsense:
When a battler has a battle animation as a pose flash effects have the actor as a target and screen effects are ignored.

**Comment by fdelapena** [comment]
Thanks @scurest, however RPG_RT seems to play both sounds in the same frame, I guess 029710c was OK already. I think it just sounds different because the playback speed adjust is not implemented yet (#349).

**Comment by Ghabry** [comment]
Concerning the one blank from of Battle Animation battlers.
A potential fix is changing back IsDone to the old behaviour:
```cpp
// battle_animation.cpp
// Battle animation line 99
bool BattleAnimation::IsDone() const {
	return GetFrame() >= GetFrames();
}
```

Completly avoid the function in sprite_battler and reset frame count one tick earlier to avoid the blank frame rendered:
```cpp
// sprite_battler.cpp line 107 
// old if (animation->IsDone())
if (animation->GetFrame()+1 >= animation->GetFrames()) {
```

**Comment by scurest** [comment]
Thanks for being patient guys.

@Ghabry, how about reverting `IsDone` and then moving the `Update` call on [L119](https://github.com/EasyRPG/Player/blob/master/src/sprite_battler.cpp#L119) up before the `IsDone` check?

**Comment by Ghabry** [comment]
@scurest  Yeah that's the best solution.

**Comment by Ghabry** [comment]
Thanks for fixing all issues, excellent job.

**Pull request merged**
