### PR TITLE
Tone: Performance improvements

### PR DESCRIPTION
**Pull request by Ghabry**
Tone change of the screen is now calculated per sprite. This means the tone is only calculated once and afterwards the Blit is normal speed as if no tone is changed. Special case is a "gradient change", when the tone changes per frame. In that case it uses the old behaviour because is faster for that case.

Gives a significant speed boost on slow hardware for that case obviously ;)

### CODE REVIEW

**Comment by Ghabry** [comment]
This could have regressions, though unlikely. Will also ask Wii people to test ;).

**Comment by BlisterB** [comment]
For mute the audio : it would be nice to modify this option in game.
For pausing the game : for example, if you open the menu, the game is not paused (it's problematic on some circumstances).

**Comment by Ghabry** [comment]
wrong topic >.>
github just lacks administration features

**Comment by Ghabry** [comment]
Got feedback in the forum, they are happy ;)

**Pull request merged**
