### PR TITLE
Refactor Game_Character classes 2 of 2

### PR DESCRIPTION
**Pull request by fmatthew5876**

### CODE REVIEW

**Comment by carstene1ns** [comment]
jenkins: test this please (newlib check).

**Comment by carstene1ns** [comment]
I do not remember where the parallax refactor was, however, needs to be adapted here.

**Comment by fmatthew5876** [comment]
This one is starting to become a blocker. I find myself needing these commits to test save games.

**Comment by fmatthew5876** [comment]
Addressed the review comments and rebased to master

**Pull request merged**
