### PR TITLE
Release 0.6.2.3

### PR DESCRIPTION
**Pull request by Ghabry**

### CODE REVIEW

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
Jenkins: test this please (stale CMake caches everywhere...)

**Review by fmatthew5876 — APPROVED** [review]

**Comment by Ghabry** [comment]
@BSzili  Sorry for generating work again :(

**Review by fdelapena — APPROVED** [review]

**Comment by BSzili** [comment]
> 
> 
> @BSzili Sorry for generating work again :(

No worries, I'll look into building it over the weekend.

**Pull request merged**
