### PR TITLE
Extend allowed tempo range for BGMs and SEs

### PR DESCRIPTION
**Pull request by rueter37**
This PR extends the allowed tempo range for BGMs and SEs from 50-200% to 10-400%.

Fixes: #2590

### CODE REVIEW

**Comment by Ghabry** [comment]
Did you make some tests to ensure that this still works fine? (I couldn't see why not but... :))

**Comment by rueter37** [comment]
Well, while the entire range works for me, I don't recommend using values below 25%. This is way too slow then (but still works).

**Comment by Ghabry** [comment]
Could you add comments to both changes?

"Normal pitch is 50 to 200 but Yume2kki uses out of range values"

**Comment by rueter37** [comment]
Comments have been added now.

**Review by Ghabry — APPROVED** [review]

**Review by fdelapena — APPROVED** [review]

**Pull request merged**
