### PR TITLE
macOS: Always link against Foundation framework 

### PR DESCRIPTION
**Pull request by Ghabry**
(fix non-SDL2 build such as libretro core)

### CODE REVIEW

**Comment by Ghabry** [comment]
Markign this as draft because this fails on Windows with:
"LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library". No idea why, I enforce "/MT" :(

**Comment by Ghabry** [comment]
I must have missed this while reading the CMake changelogs:
Since 3.15 they support a new option ``MSVC_RUNTIME_LIBRARY`` which finally solves this ``MT/MD`` chaos when using Visual Studio.
I set it now automatically based on the VCPKG triplet configuration (which means that only VCPKG works from now on when using MSVC - But we never supported anything else this is even documented).
CMake <3.15 is still supported but I issue noisy warnings.

**Comment by Ghabry** [comment]
I will tag this as "backport to stable". It is veeeery unlikely that there will be a new stable release (I can just cherry-pick these commits in the libretro fork) but just in case.

**Review by fmatthew5876 — APPROVED** [review]

**Comment by Ghabry** [comment]
Don't merge yet. I found another problem when compiling libretro-core I currently solve. ... fPIC problems >.>

**Comment by Ghabry** [comment]
now is done

**Pull request merged**
