### PR TITLE
MorphOS and AmigaOS4 build fix

### PR DESCRIPTION
**Pull request by BSzili**
I adjusted the Makefile for the latest OS4 compiler that needs some extra flags for the C++11 threads. I had to add a hack to implement to_string, I'm not sure if system.h is the right place for it, but it's used in quite a few places.

### CODE REVIEW

**Comment by Ghabry** [comment]
So there are still platforms that dont implement to_string, how unfortunate.
Not tested but another way which allows keeping the definition out of system.h is:

1. Create a string.h in the amiga folder
2. Add the amiga folder as an include dir
3. Put the stuff you added to system.h into string.h:

```cpp
INCLUDE_GUARD

#include_next <string>

#include <sstream> 
namespace std { 
	template <typename T> string to_string(const T &n) { 
		ostringstream strm; 
		strm << n; 
		return strm.str(); 
	} 
}

END INCLUDE_GUARD
```

Include_next is a GNU extension that includes the next header with this name, which is the system header and all Player code will include this file first and get std::to_string this way.

**Comment by fmatthew5876** [comment]
You can just call it `string` instead of `string.h`. Then a normal `#include <string>` in the code just works transparently. Once compilers upgrade, our fake `string` header can be removed and the code doesn't need to be changed,

I've done this `#include_next` trick before like that. Hacky but it works.

**Comment by Ghabry** [comment]
yes that was a typo, I meant "string", not "string.h". thx

**Comment by BSzili** [comment]
Mea culpa, I should have checked the C++ headers before copying the workaround I found on the forums. _GLIBCXX_USE_C99_STDIO and _GLIBCXX_USE_C99 did the trick.

**Comment by Ghabry** [comment]
I approve but can't squash merge on mobile GitHub ^^'

**Comment by carstene1ns** [comment]
Sorry, git took my master branch instead of yours when force-pushing.
(would have needed to add a different refspec)

**Pull request closed without merging**
