### PR TITLE
Fix #419, #601, #608, #673, #674 (and more)

### LINKED ISSUE #419: Crash while displaying monsters' names in RM2k battle
If you enter a battle in an RM2k game and press F12 to return to the title screen while the monsters' names are being displayed (eg. "Slime encountered"), and then start or load a game, the *next* time you enter a battle, the Player will crash when it tries to display the monsters' names.

Probably caused by the static vars in `DisplayMonstersInMessageWindow` not being reset, so the enemy iterator is bad. I think making them member variables would fix it.

### LINKED ISSUE #673: Windows: Japanese and Korean locales can't find ./RPG_RT.ldb
It seems to be an encoding issue when trying to find files with path separators in the string, crashing Player when Windows is configured with Japanese or Korean locales, which use a different directory separator (Yen an Won).

This happens always, and can't be solved by forcing the `--encoding` parameter.

To test this on Windows, follow this guide to change the locale:
http://windows.microsoft.com/en-us/windows/change-system-locale

You can check the easyrpg_log.txt also to verify the bad encoding output, even when opened as UTF-8.

### PR DESCRIPTION
**Pull request by Ghabry**
Also Implement some RPG2k3 v1.11 features

Use correct value for heal values

### CODE REVIEW

**Comment by carstene1ns** [comment]
Used in the android toolchain is boost 1.58.0, seems like boost 1.59.0 fixed some `std:` declarations.

**Comment by Ghabry** [comment]
Open for review...

**Comment by fdelapena** [comment]
It fails when loading savegames in emscripten, it shows:

    Debug: Loading save Save01.lsd
    Error: Couldn't find  save file

captura de pantalla de 2015-12-17 08-01-21

Note the 2 spaces between find and save, the filename is empty in the error message.
The save appears in the load window, so the file can be read from IndexedDB.

Could this issue have a fix in this PR or it is better on a separate PR?
It is failing already in master, so merging this PR won't affect with this.

**Comment by Ghabry** [comment]
This should work, will check

**Comment by Ghabry** [comment]
Is fixed, forgot to remove old EMSCRIPTEN related load code :D

**Pull request merged**
