### PR TITLE
Fix make distcheck, cmake build and clean build and lib folders

### LINKED ISSUE #712: Autotools: generated tarballs are tainted
It breaks when creating packages, i.e. affects OBS package generation.
It fails (FTBFS) when running `make distcheck`:

    libtool:   error: 'lib/shinonome/libeasyrpg_player_la-gothic.lo' is not a valid libtool object

The offending line seems to be there since Player 0.2 (my bad):

    EXTRA_DIST = builds lib Modules resources CMakeLists.txt src/platform

I guess the "lib" folder shouldn't be there.

### LINKED ISSUE #738: Make target "test_filefinder" is broken
Running `make` or `make test_filefinder` with CMake's Makefile results in a broken target.

    $ make test_filefinder
    [ 52%] Built target liblcf
    [100%] Built target EasyRPG_Player_Static
    [100%] Building CXX object CMakeFiles/test_filefinder.dir/tests/filefinder.cpp.o
    /home/scurest/Player/tests/filefinder.cpp:10:34: error: no member named 'ProjectTree' in namespace 'FileFinder'
                    EASYRPG_SHARED_PTR<FileFinder::ProjectTree> const
                                       ~~~~~~~~~~~~^
    /home/scurest/Player/tests/filefinder.cpp:11:4: error: C++ requires a type specifier for all declarations
                            tree = FileFinder::CreateProjectTree(".");
                            ^
    /home/scurest/Player/tests/filefinder.cpp:11:23: error: no member named 'CreateProjectTree' in namespace 'FileFinder'
                            tree = FileFinder::CreateProjectTree(".");
                                   ~~~~~~~~~~~~^
    /home/scurest/Player/tests/filefinder.cpp:30:2: error: no member named 'Init' in namespace 'FileFinder'; did you mean 'Main_Data::Init'?
            FileFinder::Init();
            ^~~~~~~~~~~~~~~~
            Main_Data::Init
    /home/scurest/Player/src/main_data.h:44:7: note: 'Main_Data::Init' declared here
            void Init();
                 ^
    4 errors generated.
    CMakeFiles/test_filefinder.dir/build.make:62: recipe for target 'CMakeFiles/test_filefinder.dir/tests/filefinder.cpp.o' failed
    make[3]: *** [CMakeFiles/test_filefinder.dir/tests/filefinder.cpp.o] Error 1
    CMakeFiles/Makefile2:283: recipe for target 'CMakeFiles/test_filefinder.dir/all' failed
    make[2]: *** [CMakeFiles/test_filefinder.dir/all] Error 2
    CMakeFiles/Makefile2:295: recipe for target 'CMakeFiles/test_filefinder.dir/rule' failed
    make[1]: *** [CMakeFiles/test_filefinder.dir/rule] Error 2
    Makefile:273: recipe for target 'test_filefinder' failed
    make: *** [test_filefinder] Error 2

### PR DESCRIPTION
**Pull request by fdelapena**
Fixes #712.

The lib folder was being included recursively, which includes the shinonome folder.
This folder was building source files which were being included into the distribution tarball.
Extra undesired files were .o, .lo and .dirstamp files and a .dist folder.
Also, these files were breaking the make distcheck build.

This PR also fixes a warning about failing to include some files in the tarball because the default tarball format (v7) does not support long paths. It has been changed to tar-ustar to prevent this issue.

The library folder should contain libraries only, so the shinonome folder has been moved into resources. This PR updates all makefiles to work with this change.

To take the opportunity to make more building changes in the same PR, doxygen and manpages have been moved to resources, which makes more sense to be there and keeps the building folder clean.

Other miscellaneous changes:
- CMake Modules folder has been moved into the builds/cmake to keep the repository root a bit lesser polluted.
- The ruby font generator now works by calling it directly on Linux without prefixing the ruby interpreter in the command line.
- CMake build works again, by working around the time_stamp test (closes #738).

### CODE REVIEW

**Comment by fdelapena** [comment]
Ready for review.

**Comment by fdelapena** [comment]
jenkins: retest this please

**Comment by Ghabry** [comment]
Well, I we can live with this solution :)

**Comment by carstene1ns** [comment]
Seems ok now, but you could rebase to do 684da5186efa511d9fcfed55c03303c60b213476, 730026184cab6bbf589ad6f39da6edbce1b96a4f and a25e84538b16dcac6c138ed891eecb5d7db465c9 all-in-one.

**Comment by fdelapena** [comment]
Ready. ^^

**Comment by carstene1ns** [comment]
I did not test the cmake stuff, but otherwise LGTM.

**Pull request merged**
