### PR TITLE
Add missing dist files

### PR DESCRIPTION
**Pull request by fdelapena**
Towards a proper fix for #1753, workaround for now with the traditional way so far, add guard headers to keep compiler building properly for other ports.

### CODE REVIEW

**Comment by Ghabry** [comment]
Don't think you need extra header guards in the header.
The header is never included so the compiler won't complain about missing symbols.

**Comment by fmatthew5876** [comment]
> Don't think you need extra header guards in the header.
> The header is never included so the compiler won't complain about missing symbols.

Is it? If you include `3ds_ui.cpp` in the automake sources for example then I think `3ds_ui.h` gets included.

**Comment by fdelapena** [comment]
That cpp file has the include guarded, so it's safe in that particular case.

I saw the guard at `audio_psp2.h` (also at `audio_libretro.h`), so it also tried to keep some consistency, but I could drop the commit anyways.

**Comment by Ghabry** [comment]
> I saw the guard at

Hm, you are right, we are just not consistent there. Keep them.

**Comment by Ghabry** [comment]
oh completely forgot this one, works for me with CMake after make dist :+1:

**Pull request merged**
