### PR TITLE
Migration on Android Studio

### PR DESCRIPTION
**Pull request by BlisterBoy**
Hello everyone !
I'm trying to finally move the android Port to Android Studio following the official documentation : http://developer.android.com/sdk/installing/migrate.html

This is a big mess, it change all the project structure and demands a lot of adaptations. So I prefer to open a Pull Request to discuss about it. I'll try to deal with this messy process the fastest possible so please wait a little if you plan to modify the android port.

 
- [x] Use the automatic Import
- [x] Adapt the ndk-build process
- [x]  Clean all the unecessary files and adapt .gitignore

Actually I'm able to launch the android port without any trouble, but it's because of the import process which moved and use the binary files to a folder, so I currently have to find a way to modify the ndk-build system to be able to deals with the android port from scratch.
And there is a lot of useless files, I supposed that it didn't created any .gitignore. Lot of things to clean !

### CODE REVIEW

**Comment by Ghabry** [comment]
Please read about .gitignore
The conversion to Android studio added lots of junk files to the repo.
Temp files, timidity files, .class files, .idea directory, generated directory

**Comment by BlisterBoy** [comment]
Soo, I manage to fix the ndk-build process, but I have to modify the android buildscript.

**Comment by Ghabry** [comment]
We can replace the ndk-build with something else if you need this (on Jenkins). I thought gradle is different to ndk-build?

**Comment by BlisterBoy** [comment]
I'm studying that and it seems that it should be just slightly different :).

**Comment by carstene1ns** [comment]
There are still quite a few immediate build artefacts in this PR that should be reviewed and removed.
For example:
-  `builds/android/.gradle/2.8/taskArtifacts/*`
- ` builds/android/app/src/main/jniLibs/*`

Then the timidity patchset should not be included in this repository:
`builds/android/app/src/main/assets/`

Also moving the translation files needs an update in the `.tx/config` file:
`builds/android/res/values/strings.xml` → `builds/android/app/src/main/res/values/strings.xml`

**Comment by BlisterBoy** [comment]
Thank you for the informations @carstene1ns , I modified the buildscript and I'm currently recompiling all the thing from scratch to be sure it's ok, and then I'll delete all the junk files.
Don't hesitate to notify me if I forgot some of them.

(Android Studio is a little tricky : a lot of tile, some of them are essential, some other just useless, with no indication).

**Comment by BlisterBoy** [comment]
Compile from scratch is ok !
Now let's clean all the files

**Comment by BlisterBoy** [comment]
I deleted all the files you specified, there are probably some other junk files, but my eyes are heavy =_=.
Good night guys !

**Comment by Ghabry** [comment]
I always thought visual studio project files suck, but Java is of course much worse :p

**Comment by BlisterBoy** [comment]
Yeah they use a strange "use everything you want" mantra, for example you can use a .xml and a .json file for configuring lint, but this is the same for everything so there is a lot of file, sometimes hard to say which one is usefull or not x).

Does the compilation works for you guys ? With the pull request in buildscripts repository.

**Comment by Ghabry** [comment]
Jenkins: Test this please.

**Comment by Ghabry** [comment]
I adjusted the buildscript in jenkins to use the one you proposed in your buildscripts pull request, the script for your case is now:

```bash
export EASYDEV_ANDROID=$WORKSPACE/../android-toolchain/android
PATH=$PATH:$EASYDEV_ANDROID/android-ndk-r10e:$EASYDEV_ANDROID/android-sdk/tools:$EASYDEV_ANDROID/android-sdk/build-tools/23.0.2/

cd builds/android

ANDROID_FOLDER=$(pwd)
cd $ANDROID_FOLDER/app/src/main

# Only compile armeabi-v7a
sed -i.bak "s/APP_ABI.*$/APP_ABI := armeabi-v7a/" jni/Application.mk

ndk-build -j3 NDK_LIBS_OUT=./jniLibs
cd $ANDROID_FOLDER
./gradlew clean
./gradlew assembleRelease

cd $ANDROID_FOLDER/app/build/outputs/apk

# shortened because doesnt matter
jarsigner && zipalign
```

But it fails with ```error: cannot find -lGLESv1_CM```

**Comment by BlisterBoy** [comment]
Uuurf, sorry for timidity!

Hmm I don't have this problem, apparently it's a library linked with OpenGL. Is it ndk-build that throw this error?

**Comment by Ghabry** [comment]
Click details next to [X] Android and then Console: https://easy-rpg.org/jenkins/job/player-android-pr/451/console

**Comment by BlisterBoy** [comment]
That comes from ndk-build

It's weird because the only things I changed with ndk-build is a new directory output, and in Android.mk with and this modification : 
PLAYER_PATH := ../../../..
to
PLAYER_PATH := ../../../../../../../
To adapt to the new file structure.

But I didn't change anything linked to the library involved in ndk-build.

**Comment by BlisterBoy** [comment]
Hmm are you sure there was no problem during the lib building process ? Or maybe a folder hasn't been exported.

Because `find . -name "*GLESv1_CM*"` give me that : 
````./android/android-ndk-r10e/platforms/android-12/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-12/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-12/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-12/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-12/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-13/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-13/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-13/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-13/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-13/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-14/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-14/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-14/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-14/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-14/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-15/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-15/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-15/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-15/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-15/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-16/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-16/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-16/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-16/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-16/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-17/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-17/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-17/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-17/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-17/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-18/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-18/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-18/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-18/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-18/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-19/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-19/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-19/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-19/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-19/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-arm64/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips64/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips64/usr/lib64/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips64/usr/lib64r2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips64/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips64/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-x86_64/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-x86_64/usr/lib64/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-x86_64/usr/libx32/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-4/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-5/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-8/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-9/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-9/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-9/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-9/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-9/arch-x86/usr/lib/libGLESv1_CM.so
./android/armeabi-toolchain/sysroot/usr/lib/libGLESv1_CM.so
./android/mips-toolchain/sysroot/usr/lib/libGLESv1_CM.so
./android/mips-toolchain/sysroot/usr/libr2/libGLESv1_CM.so
./android/mips-toolchain/sysroot/usr/libr6/libGLESv1_CM.so
./android/x86-toolchain/sysroot/usr/lib/libGLESv1_CM.so
```

**Comment by Ghabry** [comment]
No idea what's wrong there.

Something else: Is it possible, thx to gradle, to move the java code files to a sane directory?
e.g. (/src/android) so that all source files are at a common location.

**Comment by BlisterBoy** [comment]
Gradle permit those king of file manipulation, but I doubt Android Studio would agree with that.

For the lib not found library, it seems that i cannot navigate through the repo. So I can only guess that : 
- the file `./android/armeabi-toolchain/sysroot/usr/lib/libGLESv1_CM.so` hasn't been created during the android toolchain building.
- we're not pointing to the right folder in the proper Android.mk, but if the structure of the folder is the same as we were using buildscript repo, it shouldn't be that.

But as I have no visibility so I cannot decide where the problem comes from :s

**Comment by Ghabry** [comment]
As you can see in the Android.mk the sysroot folder is never used so this can't be the issue.
Because it's ndk-build it will probably look in the platform directories.
List from the server:

```
./android/android-ndk-r10e/platforms/android-12/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-12/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-12/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-12/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-12/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-13/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-13/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-13/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-13/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-13/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-14/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-14/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-14/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-14/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-14/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-15/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-15/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-15/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-15/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-15/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-16/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-16/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-16/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-16/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-16/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-17/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-17/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-17/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-17/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-17/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-18/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-18/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-18/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-18/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-18/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-19/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-19/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-19/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-19/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-19/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-arm64/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips64/usr/lib64/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips64/usr/lib64r2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips64/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips64/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips64/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-x86_64/usr/lib64/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-x86_64/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-x86_64/usr/libx32/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-21/arch-x86/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-4/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-5/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-8/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-9/arch-arm/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-9/arch-mips/usr/lib/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-9/arch-mips/usr/libr2/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-9/arch-mips/usr/libr6/libGLESv1_CM.so
./android/android-ndk-r10e/platforms/android-9/arch-x86/usr/lib/libGLESv1_CM.so
./android/armeabi-toolchain/sysroot/usr/lib/libGLESv1_CM.so
./android/mips-toolchain/sysroot/usr/lib/libGLESv1_CM.so
./android/mips-toolchain/sysroot/usr/libr2/libGLESv1_CM.so
./android/mips-toolchain/sysroot/usr/libr6/libGLESv1_CM.so
./android/x86-toolchain/sysroot/usr/lib/libGLESv1_CM.so
```

**Comment by BlisterBoy** [comment]
Hmm, the console log is not avaible anymore.

I think the problem comes from here in `buildscripts/android/Player/builds/android/app/src/main/jni/src/Android.mk` : 
````
LOCAL_LDLIBS := -L$(LOCAL_PATH)/../../obj/local/$(TARGET_ARCH_ABI) \
		-L$(EASYRPG_TOOLCHAIN_DIR)/lib -lGLESv1_CM -llog -lz \
		-llcf -lmad -logg -lvorbisfile -lvorbis -lfreetype \
		-lpixman-1 -lpng -licui18n -licuuc -licudata -lcpufeatures
```

It does a reference to lGLESv1_CM, but I cannot really understand as I'm not competent in C compilation toolchain.
If someone comes here, he is welcome to help, I'm sure it's just a little thing to adapt in this file ~__~.

**Comment by Ghabry** [comment]
Did you try the ndk-build way from your buildscript locally and did it work for you?

**Comment by BlisterBoy** [comment]
Yep all works, with the repository resulting from the import process AND from scratch (the rep "clean" from my github repository).
I was able in the two cases to go through the .apk generation and it works.

**Comment by Ghabry** [comment]
Jenkins: Test this please

okay will try a recompile after wiping the repo

**Comment by BlisterBoy** [comment]
Hmmm.. I've the feeling that the problem doesn't come from this PR but the buildscript folder of Jenkins, did you try from scratch @Ghabry ?

(I was working on the new GameBrowser, Android damn you!).

**Comment by Ghabry** [comment]
You can continue working at your Android code locally while we resolve this :D

**Comment by BlisterBoy** [comment]
Thank you Ghabry :’)
I’m currently trying to install it via a fresh new Linux VM… But I lack of free space x).
(Note for me : update the build script readme for preventing to have a Java JDK installed before using the script)

**Comment by carstene1ns** [comment]
Good news, @BlisterBoy! I was able to build the apk with your changes locally.

**Comment by BlisterBoy** [comment]
Aaaaaah yes :)

I currently have some problems with the Linux VM installation, wget for booster fails with an error 302, I suppose it's just temporarily and not linked with the Jenkins problem.

**Comment by carstene1ns** [comment]
302 is not an error, but a redirection, seems like sf.net is again in limited recovery mode...

**Comment by BlisterBoy** [comment]
Yes it redirected me through a 500 Internal Server Error x). But the problem seems to be fixed now.

**Comment by carstene1ns** [comment]
yep, but is not resolved yet. https://twitter.com/sfnet_ops
You can get issues when re-running the scripts, because @Ghabry decided it would be a good idea to remove the downloaded files after extraction ;)

**Comment by Ghabry** [comment]
objection


I have evidence that I didn't add ```rm```:
https://github.com/Ghabry/easyrpg-android-libs/commit/80fe496d0fbf3839915705e2fdc135187d6c763a

**Comment by Ghabry** [comment]
@BlisterBoy 
Feel free to remove boost :)

**Comment by BlisterBoy** [comment]
Yeah delete the archive resolved some problems (if the archive previously downloaded was an old version or a corrupted file du to a ctrl-c during the script, I faced the 2 problem). I can modify that if you want.
I delete boost :).

**Comment by BlisterBoy** [comment]
Hi guys, do I have to do something for this PR?

**Comment by Ghabry** [comment]
@BlisterBoy 
Please rebase on upstream, we can't compile this anymore because boost is gone.

**Comment by BlisterBoy** [comment]
I did the rebase, but I suppose you want me to clean this git log :O)

**Comment by Ghabry** [comment]
We talk about the git log mess later :P

I would be interested in a build that doesn't link against "GLESv1_CM". Because I can't see any GLES related linker errors in the error log.

Could you remove the "-lGLESv1_CM" item completely from Android.mk?

**Comment by carstene1ns** [comment]
jenkins: test this please

**Comment by BlisterBoy** [comment]
I rebased on upstream as demanded Ghabry, but yes it did a big mess.
Do I just have to clean the git log?
(I'm moving in an appartment, I'll do this tonight)

**Comment by carstene1ns** [comment]
No, you certainly did not *rebase*, but *merge* instead.
Well, but nevermind, we can clean that up as well. :grinning:

I will try to fix that with a local checkout and provide you with a command list to fix that locally later.

**Comment by carstene1ns** [comment]
Okay, to fix this mess we need to make sure you have the prerequisites first:
  1. the upstream remote ([howto](https://help.github.com/articles/configuring-a-remote-for-a-fork/#platform-mac))
  ```
$ git remote -v
[…]
upstream	https://github.com/EasyRPG/Player.git (fetch)
upstream	https://github.com/EasyRPG/Player.git (push)
```

  2. an updated master branch ([howto](https://help.github.com/articles/syncing-a-fork/))
  ```
$ git log --oneline -1 master
a713ce3 Merge pull request #855 from Ghabry/fastblit
```

  3. only your commits in the log
  ```
$ git log master.. --graph --oneline
*   3d26bcc Merge branch 'android' of https://github.com/BlisterBoy/Player into android
|\  
| * 0f122d2 delete junk graddle file
| * f62940c fix .tx file
| * 274836d delete timidity
| * f046757 delete jniLibs
| * af5e4e0 fix "MissingTranslation" error
| * df4b450 fix ndk-build
| * e09d2f2 Add a gitignore and delete build folder
| * a67611e Follow instruction to build and launch the project
| * 5da8859 Import to Android Studio
* a28937f fix "MissingTranslation" error
* 126c446 fix ndk-build
* e2c0201 Add a gitignore and delete build folder
* f3e8831 Follow instruction to build and launch the project
* b1fc2a8 Import to Android Studio
```

Now we can rebase the the android branch on master
```
$ git checkout android
$ git rebase -i master
```
In the rebase editor remove the duplicated commits b1fc2a8, f3e8831, e2c0201, 126c446 and a28937f.
Also squash the commits e09d2f2, f046757, 274836d and 0f122d2 into 5da8859.

Let the rebase finish and observe the log:
```
$ git log master.. --graph --oneline
* 3d4a74a fix .tx file
* c433905 fix "MissingTranslation" error
* c0c43e8 fix ndk-build
* e0a601e Follow instruction to build and launch the project
* 40819c7 Import to Android Studio
```

Then, after all is ok, do a forced push of your branch to github:
```
$ git push -f origin android
```

Here is an asciicast of the procedure: https://asciinema.org/a/dj2iju2q1ae1grkpd49keqjgz

**Comment by BlisterBoy** [comment]
I swear I found the procedure on a tutorial explaining how to rebase on upstream :''[[[[[[[.
But thanks 1000 times for the tutorial, I bookmarked it!

**Comment by Ghabry** [comment]
Did you really follow @carstene1ns description? You created again a merge commit and your duplicate commits are still there.

I wonder if github detects when I check out this branch, rebase it and push it to master and auto closes this one. :D

**Comment by BlisterBoy** [comment]
Hello guys
Sorry I did all the @carstene1ns instructions, which were very clear -thanks again I bookmarked this-, but I was unable to the the final push because of my internet connexion (I just mooved in an apartment and I use my android shared connexion and it's not really good). I always stayed stuck at ~40% -___-.

Sorry for the time lose, and thank you @Ghabry !

**Pull request closed without merging**
