### PR TITLE
Back button call menu in ButtonMapping Activities

### PR DESCRIPTION
**Pull request by BlisterBoy**

### CODE REVIEW

**Comment by BlisterBoy** [comment]
I remembered that in Player Activity, back button ask a confirmation to quit the game.

Should I delete this behavior to call the menu too ?
Pro : 
- Less complicated GUI
- Fix definitively #442

**Comment by fdelapena** [comment]
Because some recent devices don't have hardware menu buttons (only home and back buttons), I think any hardware involved menu button should be removed. Adding an action bar for this and stealing space in the game screen is ugly so this feature could be added to the back button instead.

A good device example without this button: HTC One.

**Comment by BlisterBoy** [comment]
@fdelapena there is no hardware button involved in the android port :p . (My phone doesn't have such a button and I have no problem).
When we associate a menu to an activity, it creates an hamburger icon in the dock (software button) to reach the menu .

But I think I'll associate the menu to back button to the Player Activity, because back button is already associated to a pop-up box (asking for stopping the game).

**Comment by BlisterBoy** [comment]
Done !

**Comment by Ghabry** [comment]
Thanks for the fix. Just got back from a short weekend trip. Will check tomorrow :)

**Comment by fdelapena** [comment]
Tested here, back button works for adding/editing from the screen button layout editor with latest pull request generated .apk :+1:.

**Comment by Ghabry** [comment]
Sorry that this took so long, was without internet the last days.
Works perfect, thx.

**Comment by Ghabry** [comment]
One issue is still that the config function of the Game Browser is not obvious.
Similiar for long press to select region.

**Comment by fdelapena** [comment]
These UX issues have been reported at #512 some days ago.

**Pull request merged**
