### PR TITLE
FileFinder: Support directory symlinks on linux

### PR DESCRIPTION
**Pull request by fmatthew5876**
On linux, master won't let you point to a `--project-path` which is a symlink to a game directory.

### CODE REVIEW

**Comment by Ghabry** [comment]
Jenkins: Test this please
Some jobs didn't fire...

**Comment by fmatthew5876** [comment]
Fixed

**Comment by fmatthew5876** [comment]
jenkins: test this please

**Comment by Ghabry** [comment]
This was suggested by oech on twitter months ago btw.

**Pull request merged**
