### PR TITLE
Custom Resolution 3/?, Config 4/?

### PR DESCRIPTION
**Pull request by Ghabry**
draft because:

- ~~Android part is missing / broken~~
- ~~help/manual page update needed~~

~Depends on #2913~

------------

Commits explained:

1. Refactors the config param class already. Ini reading is now a method which simplifies the code alot and reduces the errors.
2. Adds a new resolution setting to "Video" for enabling (ultra)widescreen mode. 
3. When a resolution is set through the settings the metrics are now faked. Improvies game compat because e.g. pictures are centered. Is not perfect.
4. (adds Exit Game option)
5. Adds support for new game specific settings in a EasyRPG.ini file in the game folder. There is no gui to configure this (not planned yet, this was faster) but can be used to configure how the engine behaves.

Possible keys in EasyRPG.ini @florianessl

```ini
[Game]
NewGame=1 <- Skip the title screen
FakeResolution=1 <- When WinW/WinH is used, enables 320x240 resolution faking
Engine=rpg2k <- Engine override (see --help for options)

[Patch] <- Patch override, keys named after the existing patches
Maniac=1
DynRPG=1
CommonThisEvent=1 <- This Event in Common Events, default in 2k3E
PicUnlock=1 <- Messages are non-blocking for pictures, default in 2k3E
```

### CODE REVIEW

**Comment by fdelapena** [comment]
jenkins: test this please :heart:

**Comment by Ghabry** [comment]
Bet I will regret this soon but whatever:

image

**Comment by Ghabry** [comment]
Rebased and reapplied a commit that somehow got lost (was originally in "fixes" branch, must have deleted it by accident)

**Review by fdelapena — APPROVED** [review]
Appreciated features, and per-game ini settings is going to be so useful for game developers :+1:.

**Pull request merged**
