### PR TITLE
android app - Thai translation

### PR DESCRIPTION
**Pull request by pureexe**
Add Thai translation for Android app
I hope Easy-RPG Player will render Thai character correctly.

Cheer!

### CODE REVIEW

**Comment by Ghabry** [comment]
@carstene1ns Is it possible (without too much work) to get this on transifex.

Thai rendering for Player will come this year.

**Comment by carstene1ns** [comment]
Yep, this can be pushed from the command line, but maybe needs to setup the language on transifex before (does not really matter, can just be pushed again after setup).

**Comment by carstene1ns** [comment]
done, `$ tx push -t -l th` did all the necessary setup.
LGTM

**Comment by Ghabry** [comment]
Thanks, this translation will ship in the next Android release.

**Pull request merged**
