### PR TITLE
Fix OGG in emscripten (hopefully)

### PR DESCRIPTION
**Pull request by Ghabry**
Fix OGG playback when system frequency is 48k and OGG 44.1k (same as the WAV bug)

### CODE REVIEW

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by Ghabry** [comment]
No idea why but Midi is now broken :O

**Comment by fdelapena** [comment]
Jenkins: Test this please

**Comment by fdelapena** [comment]
Jenkins: Test this please

**Comment by fdelapena** [comment]
Jenkins: Test this please

**Comment by carstene1ns** [comment]
jenkins: test this please =)

**Comment by fdelapena** [comment]
The PR needs merge conflict resolution, can't be merged currently.

**Comment by Ghabry** [comment]
yeah, I'm currently checking something

**Pull request merged**
