### PR TITLE
Battle improvments

### LINKED ISSUE #397: Spell drain not implemented
Spells draining magic from the target and giving it to the source don't work

Test case "Blut saugen" spell in Vampires Dawn:
> In this game the Vampires have the ability to suck blood in the battle (from an opponent which has blood), but after using the ability no blood is gained, so this attack is useless.

Reported by Darkztar

### LINKED ISSUE #529: Bug in Wadanohara: Battle against Sal
Hello
I found a bug in wadanohara,this time is in the battle against sal
when the battle was supposed to end the game window just closes making it impossible to end the battle
this battle is diferent from other battles,this one ends after a certain number of turns(or after sal said  everything he had to say,not sure)
i hope this bug gets fixed easly
hugs :D

### LINKED ISSUE #550: Battle: skill attack allows to target already dead enemies
How to reproduce:

Tested with game Off (English translation 2.0):

    easyrpg-player window battletest 22

First attack: Select "Competence", "Furious homerun", target first Magnolia. It should hopefully die.
Second attack: "Competence", "Awaited Embrance", target third Magnolia (it won't blink). It will crash, at least here.

Tested under other circumstances with other enemy groups. Because it allows to target already unexisting battlers sometimes it may attack to allied, sometimes attack nobody and also sometimes it may crash. The backtrace when crashing is:
```gdb
Program received signal SIGSEGV, Segmentation fault.
0x0000000000500be8 in Game_Battler::HasState(int) const ()
#0  0x0000000000500be8 in Game_Battler::HasState(int) const ()
#1  0x0000000000500dc1 in Game_Battler::IsDead() const ()
#2  0x0000000000569252 in Game_BattleAlgorithm::Skill::IsTargetValid() ()
#3  0x000000000054ed4d in Scene_Battle_Rpg2k3::ProcessBattleAction(Game_BattleAlgorithm::AlgorithmBase*) ()
#4  0x000000000054e9f9 in Scene_Battle_Rpg2k3::ProcessActions() ()
#5  0x000000000053451d in Scene_Battle::Update() ()
#6  0x000000000054d3c8 in Scene_Battle_Rpg2k3::Update() ()
#7  0x000000000043897d in Player::Update(bool) ()
#8  0x000000000045252e in Scene::MainFunction() ()
#9  0x000000000043867f in Player::MainLoop() ()
#10 0x0000000000438608 in Player::Run() ()
#11 0x000000000042ca25 in main ()
```

### LINKED ISSUE #551: OFF: Battle against The Judge hangs
Tutorial hangs

[just wanted an issue number for this]

### LINKED ISSUE #554: Battle animations that change the screen tone show black background for transparent pixels
~~Not detected in battle scenes so far, only when used in map.~~
This bug affects multiple games. Needs a test case yet.

### LINKED ISSUE #555: Battle: victory when attacking to multiple targets only hides the first enemy killed
When attacking to 2 or more targets, if the attack kills them to trigger victory, it should make disappear all targets, but only hides one of them.
Verified at least in 2k3 battles. Not tested in 2k.

### LINKED ISSUE #564: Battle: sporadic crash after winning some battle groups in Off game
This crash in Off game (English translation 2.0) is hard to get sometimes, last attempt I needed to defeat around 20 groups before getting it:

    easyrpg-player --window --new-game --start-map-id 335 --start-party 12 --start-position 2 12

Backtrace:

```dtrace
Program received signal SIGSEGV, Segmentation fault.
0x0000000000432857 in Graphics::SnapToBitmap () at src/graphics.cpp:218
218			(*it_list)->Draw();

#0  0x0000000000432857 in Graphics::SnapToBitmap () at src/graphics.cpp:218
        it_list = 
#1  0x0000000000432917 in Graphics::Freeze () at src/graphics.cpp:229
No locals.
#2  0x0000000000432a1c in Graphics::Transition (
    type=Graphics::TransitionZoomOut, duration=32, erase=false)
    at src/graphics.cpp:249
No locals.
#3  0x0000000000458f46 in Scene_Map::TransitionIn (this=0x2e990c0)
    at src/scene_map.cpp:89
No locals.
#4  0x00000000004562a1 in Scene::MainFunction (this=0x2e990c0)
    at src/scene.cpp:88
        init = false
        __PRETTY_FUNCTION__ = "virtual void Scene::MainFunction()"
#5  0x000000000043dc53 in Player::MainLoop () at src/player.cpp:178
No locals.
#6  0x000000000043dbdc in Player::Run () at src/player.cpp:173
No locals.
#7  0x0000000000431f15 in main (argc=2, argv=0x7fffffffdf98)
    at src/platform/sdl_main.cpp:31
No locals.
```

### PR DESCRIPTION
**Pull request by Ghabry**
The map interpreter works pretty well now, but battle... Hope this makes it a bit better

Fixes #550 
Fixes #529 
Fixes #551
Fixes #397
Fixes #564
Fixes #554
Fixes #555

Implements parts of #278

Needs feedback after:
#523

### CODE REVIEW

**Comment by BlisterBoy** [comment]
Great pull request Ghabry !

**Comment by Ghabry** [comment]
image9image9

**Comment by BlisterBoy** [comment]
omg Ghabry is on fire

**Comment by Ghabry** [comment]
That's enough from my side. Open for review

**Comment by Ghabry** [comment]
Okay found another critical bug... meh

**Comment by Ghabry** [comment]
That's enough from my side. Open for review again ;)

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by CoreBerlin** [comment]
Hi, Fixes #397 is really necessary for playing Vampires Dawn, because it most useful Spell and Vampires going into Rampage, when they reach the low mark (yellow numbers).
Besides it is not only absorbing the hp to your sp - if they are bleeding, they lose hp every round

**Pull request merged**
