### PR TITLE
Save game compatibility fixes for regtesting

### PR DESCRIPTION
**Pull request by fmatthew5876**
For #2297

### CODE REVIEW

**Comment by fmatthew5876** [comment]
For the states thing I tested:

- [x] actor in starting party - array saved
- [x] actor added to party - array saved
- [x] actor never in party - array clear
- [x] actor failed to add because party full - array clear
- [x] state added to actor not in party - array saved
- [x] state which actor doesn't have, removed from actor not in party - array saved

**Comment by Ghabry** [comment]
I observed now something strange: When I save manually I get this 0 0 0 0 0 0 0 0 thing but when I use ``game_system->save`` from DynRPG the states array is empty. So there must be some preprocessing here. Have to check the assembly.

**Comment by Ghabry** [comment]
Figured it out: This is some obscure RPG_RT stuff: The "<status>" is empty for all units UNTIL you move or open a scene.

This is not worth emulating, will try to patch this. Thanks for the other fixes though!

**Comment by fmatthew5876** [comment]
> The resize happens the first time a condition is read. In RPG_RT this happens when moving because of a condition damage step (poison) or when opening the Menu scene. I can inject a function call that "touches" the states or _do you want to emulate this_?!

I would really prefer not to, this is hacky and bad for performance. Also it means a simple getter function can no longer be const. This whole change is hacky, would it make sense just to touch all the states for all actors in DynRPG when starting up?

**Comment by Ghabry** [comment]
Great. Now the only incompatibilities are: 

- ``title.timestamp``
- ``system.scene`` <- can patch this in dynrpg
- ``easyrpg.version``

Any good API idea for setting timestamp and version to 0?

**Comment by fmatthew5876** [comment]
> * `system.scene` <- can patch this in dynrpg

Why don't we fix this Player, it kind of makes sense, especially for the maniac patch save feature.

When saving, we can look at the scene type at the top of the scene stack and map it back to the RPG_RT scene type.

> * `title.timestamp`
> * `easyrpg.version`

Timestamp needs a patch to liblcf to allow overriding the time in `LSD_Reader::PrepareSave`. Version could be added as an argument to the save function as it's already passed in.

Let's take a step back however. While we can patch these, what happens later when we start support RPG_RT patches with custom save chunks? Or easyrpg custom features?

**Comment by Ghabry** [comment]
> Why don't we fix this Player, it kind of makes sense, especially for the maniac patch save feature.

Oh right I forgot the Maniac Patch. Yes, better fix this.

> Timestamp needs a patch to liblcf

Actually why don't we just skip the LSD PrepareSave call when doing the regression test recording.
I have to manually patch the save_count for DynRPG anyway so just skipping these 3 lines is actually better.

```
++save.system.save_count;
save.title.timestamp = LSD_Reader::GenerateTimestamp();
save.easyrpg_data.version = version;
```

> Let's take a step back however. While we can patch these, what happens later when we start support RPG_RT patches with custom save chunks? Or easyrpg custom features?

I'm not sure what you mean with custom RPG_RT save chunks. Nothing like this exists right now. Do you think about future patches?

For EasyRPG custom features... Well, one could record a proper input when the feature is invented and then use this recording for regression testing?

**Comment by Ghabry** [comment]
If you want to get rid of the RPG_RT status compat commit: I added probing. Couldn't find this in the DynRPG header:

```
for (int i = 0; i < RPG::actors.count(); ++i) {
	RPG::Actor* actor = RPG::actors[i + 1];
	asm volatile("call *%%esi"
		:
		: "S" (0x4BFF8C), "a" (actor), "d" (1)
		: "ecx", "cc", "memory");
}
```

I have no idea why it must be "S", when I change this I get a runtime error o.O  But it works!

**Comment by fmatthew5876** [comment]
added the requested items,

Removed the status stuff, but left it as a reverted commit unless we change our minds later.

**Comment by Ghabry** [comment]
made a quick test. Should be fine this way.

Keep it as is for now. Will continue working on this at the weekend - is a complex problem.

**Review by Ghabry — APPROVED** [review]
I do all my regtests with these commits picked so they work. Pls just remove the state commit+revert.

The "Touching" of the states through a plugin works fine. And stuff like "subhook junk data" shows that patching RPG_RT data can't be fully avoided for our use case.

**Comment by fmatthew5876** [comment]
Removed the states commits

**Pull request merged**
