### PR TITLE
Branch loop limit workaround

### LINKED ISSUE #1707: Interpreter execution test cases
~~Events run for up to 10k iterations and then force exit. I found one test case where we don't match, so I'm writing test cases here.~~

General set of set cases for how the interpreter actually executes event code.

### PR DESCRIPTION
**Pull request by fmatthew5876**
Depends on #1628 

Fixes: #1613

### CODE REVIEW

**Comment by Ghabry** [comment]
You fixed loop limit stuff but you ignored the comment in game_interpreter mentioning this:
Guess this commit also means that the skipping is in general a problem and the real fix is skipping to the "End" command instead of the command after.
```
// FIXME?
// After calling SkipTo this index++ will skip execution of e.g. END.
// This causes a different timing because loop_count reaches 10000
// faster then Player does.
// No idea if any game depends on this special case.
```

**Comment by fmatthew5876** [comment]
I missed that one. I just did quick tests of some commands with conditionals. Will take a deeper look at this. Maybe better to fix skip than add hacks like this.

**Comment by Ghabry** [comment]
I can already tell you that I event traced this and it will indeed execute the "End" event.
Not sure about "Else" though, need to recheck this but wouldn't make sense when this executes.

**Comment by fmatthew5876** [comment]
So we can test this SkipTo behavior with the way opensavemenu allows other events to run only a single command. Essentially it would let us single step through event code and see where the index goes each time.

I will setup tests in #1707

**Comment by fmatthew5876** [comment]
So the real reason we aren't matching the loop limit here is because we don't correctly emulate branching commands and the `subcommand_path` chunks.

I will fix that in a later PR. For now I am leaving this one open as the current solution is a workaround which fixes #1613.

**Pull request merged**
