### PR TITLE
3DS: Replace the banner with a shiny EasyRPG 3D logo

### PR DESCRIPTION
**Pull request by Ghabry**
Created by FONZD

It looks like this one: https://gbatemp.net/threads/easyrpg-3ds-rpg-maker-2000-2003-player-for-3ds.419889/page-8#post-6305449

but without the front EasyRPG logo and with some wording fixed (player -> Maker, port -> Port)

[the golden background is the 3DS Menu skin of him, not part of the banner]

### CODE REVIEW

**Comment by Ghabry** [comment]
For testing purposes: https://easy-rpg.org/downloads/easyrpg-player-cia.zip

**Comment by Rinnegatamante** [comment]
I think without the little logo in 2D and with centered texts it should be better but it's only a personal preference :P

**Comment by Ghabry** [comment]
As written it's without the front logo. But you are right about the centering, will check this.

**Comment by Ghabry** [comment]
yepp is centered 

unbenannt

**Pull request merged**
