### PR TITLE
Android: Migrate to AndroidX

### LINKED ISSUE #2018: Android: migrate from deprecated support library to AndroidX
https://developer.android.com/jetpack/androidx/migrate

### PR DESCRIPTION
**Pull request by BlisterB**
This PR address. Fix #2018 

I've upgrade to the last version of Gradle, corrected the warning/problems it produced and then migrated to AndroidX and SDK29.
The project is now up to date with Android requirements.

Please note that this PR is linked to #2259 and #2258.

### CODE REVIEW

**Comment by Ghabry** [comment]
For some reason you just installed random nonsense like the Android emulator on the system :/. I hate gradle.

Iirc the reason why I never updated gradle is that I don't want bloatware like the grade deamon 🤔. 
Google is annoying.

**Comment by BlisterB** [comment]
> For some reason you just installed random nonsense like the Android emulator on the system :/. I hate gradle.

Arf yes Gradle seems to perform unnecessary tasks.
I upgraded to Gradle 4.0.0 and SDK 28 because it was a prerequisite for AndroidX. Then I fixed some warnings/problems (such as removing targetSDK/minimalSDK in AndroidManifest.xml). Then I upgraded to AndroidX and SDK29 (and fixed other warnings/problems). 
I only used the dedicated GUI in Android Studio as requested in the official Documentation, so I didn't perform unnecessary task from my side.

The problem seems to be linked with NDK, there must be a way to make this compatible again 🤔.

**Comment by Ghabry** [comment]
@BlisterB   can you rebase this?

**Comment by BlisterB** [comment]
Done :).

**Comment by Ghabry** [comment]
thanks now I only have to figure out how get a succesful build .... Android -_-

**Comment by Ghabry** [comment]
Jenkins: test this please    - need the latest error again

**Comment by Ghabry** [comment]
@BlisterB 
Sorry, can you rebase this again? I manually installed android-29 now, maybe this works.
This doesn't compile anymore because your Player code is too old. ;)

**Review by fdelapena — APPROVED** [review]

**Comment by Ghabry** [comment]
Oh wow. It compiled 🥳 .

Only have to test it now on various devices

**Comment by Ghabry** [comment]
Have one stupid bug: when I scroll the game browser the app freezes. Logcat follows later.

Everything else works.

**Comment by BlisterB** [comment]
Oh this is strange: I look at this as soon as possible :).

**Comment by Ghabry** [comment]
here is an unfiltered logcat but it looks useless: https://gist.github.com/Ghabry/29fd179979591ae3c3eeb67214e36723

Maybe searching for the view helps. The game list is a RecyclerView?

**Comment by Ghabry** [comment]
Oh Android also writes a ANR dump of all running threads into "/data/anr" though without root you can't read these files so you are fcked. Great. Good that I root everything.

The problems appears to be my XYZ Image Decoder for the Game Browser: (but why now??? This is used since years)

````

"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x79b6b7a8 self=0x7e64814c00
  | sysTid=9325 nice=-10 cgrp=default sched=0/0 handle=0x7eea700548
  | state=R schedstat=( 16247128700 21147238 582 ) utm=1622 stm=1 core=7 HZ=100
  | stack=0x7fdacf1000-0x7fdacf3000 stackSize=8MB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/9325/stack)
  native: #00 pc 000000000004470c  /data/app/org.easyrpg.player-vn_UCpwflzQub5camAAr3A==/lib/arm64/libgamebrowser.so (std::__ndk1::__vector_base<unsigned char*, std::__ndk1::allocator<unsigned char*>>::~__vector_base()+180)
  native: #01 pc 00000000000433cc  /data/app/org.easyrpg.player-vn_UCpwflzQub5camAAr3A==/lib/arm64/libgamebrowser.so (std::__ndk1::vector<unsigned char*, std::__ndk1::allocator<unsigned char*>>::~vector()+20)
  native: #02 pc 0000000000042b64  /data/app/org.easyrpg.player-vn_UCpwflzQub5camAAr3A==/lib/arm64/libgamebrowser.so (Java_org_easyrpg_player_game_1browser_GameScanner_decodeXYZ+2240)
  at org.easyrpg.player.game_browser.GameScanner.decodeXYZ(Native method)
  at org.easyrpg.player.game_browser.GameScanner.getGameTitleScreen(GameScanner.java:145)
  at org.easyrpg.player.game_browser.GameBrowserActivity$MyAdapter.onBindViewHolder(GameBrowserActivity.java:227)
  at org.easyrpg.player.game_browser.GameBrowserActivity$MyAdapter.onBindViewHolder(GameBrowserActivity.java:183)
  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6476)
  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6509)
  at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5452)
  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5718)
  at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
  at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
  at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
  at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
  at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:201)
  at android.app.ActivityThread.main(ActivityThread.java:6815)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

Verified this by deleting the libgamebrowser.so from /data/app/org.easyrpg via root.

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
After wiping the workspace, rebuilding, then updating the CI script because the output APK suddenly moved from ``builds/android/app/build/outputs/apk`` to ``builds/android/app/build/outputs/apk/release`` (wtf) this is working.

There was a silly bug in the XYZ code: The vector was declared as ``std::vector<uint8_t*>`` and then used as ``std::vector<uint8_t>`` in libpng code. Don't ask me why this worked for 4 years o_O.

Then crashed by memory corruption I guess (ANR stacktrace shows the destructor). Also WTF: Why does segfaulting in an event handler ANR instead of crashing?!?!?!?!?!

**Review by Ghabry — APPROVED** [review]
Tested this on the devices I have:

- Android 4.0.4
- Android 4.1.2
- Android 9

Works great.

On 4.1.2 I tested the mail bug report feature -> Works.

4.0 devices have no TLS 1.2, so they can't even access our website... 4.1 - 4.4 depends on the company.

Pushing this to beta to find problematic devices

**Review by fmatthew5876 — APPROVED** [review]

**Comment by Ghabry** [comment]
If you get PR builder error now please rebase your PR once

**Pull request merged**
