### PR TITLE
Rename event interpreter chunks (liblcf#311)

### PR DESCRIPTION
**Pull request by fmatthew5876**
Depends on https://github.com/EasyRPG/liblcf/pull/311

### CODE REVIEW

**Comment by fmatthew5876** [comment]
jenkins: test this please

**Comment by fmatthew5876** [comment]
Rebased to master and https://github.com/EasyRPG/liblcf/pull/311

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by Ghabry** [comment]
I added experimental liblcf dependency handlng to the buildbot, requires liblcf#NUM in the issue title.
Because this is rather ugly only did it for Linux, so you have one checkmark for orientation.

**Comment by carstene1ns** [comment]
test this please

**Pull request merged**
