### PR TITLE
Implement 2k3 Death Handlers

### PR DESCRIPTION
**Pull request by fmatthew5876**
Fix: #1648 

~~Depends on: https://github.com/EasyRPG/liblcf/pull/340~~
~~Depends on: #1881~~

### CODE REVIEW

**Comment by fdelapena** [comment]
Test this please.

**Comment by fmatthew5876** [comment]
I've rebased this onto #1881 

I've verified the behavior of the death teleport w.r.t. the concerns in #1881 . It behaves the same as a parallel event teleport.

I've also verified that while RPG Maker 2003 editor sets both `death_handler_1` and `death_handler_2` chunks, RPG_RT only uses the `death_handler_2` chunk to determine whether or not to invoke death handlers.

**Comment by fmatthew5876** [comment]
https://github.com/EasyRPG/liblcf/pull/340

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by fmatthew5876** [comment]
Jenkins: test this please

**Comment by fmatthew5876** [comment]
I've tested this game for edge cases and interpreter behavior surrounding death handlers.

It would be really great if someone else could sanity check everything by just playing some games that use death handlers to double check.

**Comment by Ghabry** [comment]
The only game I know of is Monigote Fantasy and this works :+1:

**Pull request merged**
