### PR TITLE
window_equipstatus: Draw fullwidth arrow in Japanese games

### PR DESCRIPTION
**Pull request by kakurasan**
See screenshots.

RPG_RT on Windows:
equip_arrow_rpgrt
EasyRPG Player (Unpatched):
equip_arrow_unpatched
EasyRPG Player (Patched):
equip_arrow_patched

### CODE REVIEW

**Comment by kakurasan** [comment]
Official Japanese version of RPG Maker 2k (called "RPG Tkool 2000") generates the `RPG_RT.exe`. This means all Japanese rpg2k games contain the version of `RPG_RT.exe`.

**Comment by Ghabry** [comment]
@kakurasan 
The item count uses a : instead of X in your screenshot. Is that also Jp rpgrt specific?

**Comment by kakurasan** [comment]
I don't know much about non-Japanese rm2k/2k3 games, but screenshots in [this article](https://rpgmaker.net/articles/1307/) show that English games, too, draw ":".

I think fullwidth "：" is more suitable than halfwidth ":".
Fullwidth:
item_num_fullwidth_colon
Halfwidth:
item_num_halfwidth_colon

**Comment by Ghabry** [comment]
hm, this : vs x should be checked. but not here. merging

**Pull request merged**
