### PR TITLE
Transifex integration

### PR DESCRIPTION
**Pull request by carstene1ns**
This modified a lot of whitespace, use this URL https://github.com/EasyRPG/Player/pull/617/files?w=0 to only show "real" changes.

### CODE REVIEW

**Comment by BlisterBoy** [comment]
Are we supposed to use Transifex to translate the app now ? I didn't know this service, it doesn't seems to not be free

**Comment by Ghabry** [comment]
Transifex is a user friendly service for submitting translations and it's free for Open Source projects. (for others it's expensive, yes)

**Comment by carstene1ns** [comment]
@BlisterBoy: Don't worry, you can still translate locally and use a pull request, if you want.
However, it is also possible (and easy) to translate locally and just 'push' the translation to transifex instead of github.
All of this needs some documentation to be written.

**Comment by BlisterBoy** [comment]
Okay ! I'll check out how it works

**Comment by carstene1ns** [comment]
I am also open for alternatives, however most of them do not offer a free membership, some which do are:
 * http://www.oneskyapp.com/
 * https://crowdin.com/page/open-source-project-setup-request

Others would need to be hosted and maintained by ourselves:
 * https://weblate.org/
 * http://pootle.translatehouse.org/
 * http://zanata.org/

**Comment by BlisterBoy** [comment]
Don't worry I wasn't denigrating this option, I just have no knowledge on that domain ^^. You already did a work to adapt the project to this platform, if there is no reason to use another option, better not loose the time you spent on it :).

**Comment by carstene1ns** [comment]
I tried to make the comments a bit better. This one should be ready now.

**Pull request merged**
