### PR TITLE
Expand grayscale bit depths < 8, needed with libpng 1.2 (fixes #635)

### LINKED ISSUE #635: Grayscale PNGs with lesser than 8 bit depth display garbage with libpng 1.2
This old issue is frequently reported by Google Play users issue and only seems to happen with current Android builds. It can be reproduced in emulators fortunately.

captura de pantalla de 2015-10-17 23-11-29
captura de pantalla de 2015-10-17 23-17-37

### PR DESCRIPTION
**Pull request by fdelapena**

### CODE REVIEW

**Comment by Ghabry** [comment]
Thanks for the fix. I won't find time this year to update the Android build voodoo system.

**Comment by carstene1ns** [comment]
LGTM

**Comment by Ghabry** [comment]
is that one ready?

**Comment by fdelapena** [comment]
Yeah.

**Pull request merged**
