### PR TITLE
Remove SaveMapInfo Setup and Fixup - depends on liblcf #403

### PR DESCRIPTION
**Pull request by fmatthew5876**
Depends on: https://github.com/EasyRPG/liblcf/pull/403

### CODE REVIEW

**Review by fdelapena — APPROVED** [review]

**Comment by Ghabry** [comment]
Are the test failures related to missing liblcf merge?

**Comment by fmatthew5876** [comment]
all tests pass on windows / WSL for me

**Comment by Ghabry** [comment]
try rebasing, maybe some commit that fixed this is missing

**Comment by fmatthew5876** [comment]
Rebased, but the crashing test is because `map_info.upper_tiles` is now initialized inline in the lcf PR instead of in `Setup()`. Since setup is no longer called here, and the old liblcf initializes it to empty, we dereference out of bounds and crash.

**Comment by Ghabry** [comment]
ah you have a  "liblcf #403" line in the title, so the Linux PR builder uses this PR version. This explains why Linux has a checkmark. Nevermind.

**Comment by Ghabry** [comment]
Jenkins: test this please
(somebody pls merge this later, going to bed)

**Review by Ghabry — APPROVED** [review]

**Pull request merged**
