### PR TITLE
Add some new/missing strings before 0.4.1

### PR DESCRIPTION
**Pull request by carstene1ns**
Let's keep this open, maybe there will be some late additions before the new version.

### CODE REVIEW

**Comment by carstene1ns** [comment]
Our translators seem to have no time currently :disappointed:…

**Comment by Ghabry** [comment]
Well they still have ~2 weeks till release :sob:

**Comment by fdelapena** [comment]
@tomyun translated strings into Korean in Transifex, thank you!

**Comment by carstene1ns** [comment]
This should be ready.

**Comment by carstene1ns** [comment]
@BlisterBoy: Do you think you can provide the new/missing strings in French this week on transifex? Thanks!

**Comment by BlisterBoy** [comment]
I plan to retranslate all the app, but un 2 week, hard study time right now!

**Pull request merged**
