### PR TITLE
Small fixes for 3DS and warnings

### PR DESCRIPTION
**Pull request by carstene1ns**
Needed after #1973.

### CODE REVIEW

**Comment by Ghabry** [comment]
OSX does not have _DIRENT_HAVE_D_TYPE defined but d_type is properly populated. I slowly think that this is a hugher problem. Anybody with a BSD system around to check if this macro is defined there? The manpage says "this is a BSD extension" but OSX is BSD based >.>

**Comment by Ghabry** [comment]
Proposed solution by LLVM (6 months ago): https://reviews.llvm.org/D64940

**Comment by carstene1ns** [comment]
This solution seems ok for now.

**Comment by fmatthew5876** [comment]
Confirmed on FreeBSD 12 that `_DIRENT_HAVE_D_TYPE` is not defined when you `#include <dirent.h>`

**Pull request merged**
