### PR TITLE
Button mapping rebuild + Fix #437

### LINKED ISSUE #437: Touch problem : sliding doesn't supported
Hi everyone,

On the Android port there is a problem you've probably already noticed : 
When you press a button, the action is detected but if you slide out of the button area, the app doesn't take it into account.

For example if I start to press the UP BUTTON, the character goes up, but if I slide to the RIGHT BUTTON, the character continues to go up.
This example works for every buttons.

(Is that normal that I can't choice label for issues ?)

### PR DESCRIPTION
**Pull request by BlisterBoy**
Hi everyone !

So this is my work related to #438 . All the Button Mapping has been rebuild :
:+1: The code is now clearer
:+1: Modular
:+1: Ready to implement #288 :smiley: 
:+1: The Buttons now display the letter associated (always to be ready for #288 )

I also fixed #437 , you can now move your character by sliding your finger on the Virtual Cross, and there is no more "infinite race" when you slide out the Virtual Cross ! I think players will enjoy that features :smile: .

### CODE REVIEW

**Comment by BlisterBoy** [comment]
(I forgot : now the app supports multitouch)

**Comment by Ghabry** [comment]
Trying to enable Android PR builder...

Jenkins: Test this please <3

**Comment by Ghabry** [comment]
test this please

**Comment by Ghabry** [comment]
BlisterBoy does this still need the Finger Code in C++ now?

The stuff in the __ANDROID__ block here:
https://github.com/EasyRPG/Player/blob/master/src/sdl_ui.cpp#L879

And if not needed anymore remove getScreenHeight, getScreenWidth, getPixels (they are invoked via JNI)

**Comment by Ghabry** [comment]
Your code needs a rebase on master. There was an incompatible update in liblcf during last week. Please update your version of liblcf.

If you havn't configured upstream repo already for Player:
```
git remote add upstream git@github.com:EasyRPG/Player.git
```

Then:
```
git fetch upstream
git rebase upstream/master
```

Hopefully this works without any conflicts...
Then do a forced push.

**Comment by BlisterBoy** [comment]
Oh, from Eclipse I didn't saw that part of code. Nope the Android port doesn't required it anymore, should I delete it ?

I'll follow your instruction relative to the merge

**Comment by BlisterBoy** [comment]
Thanks for the explanations Ghabry :) !

**Comment by Ghabry** [comment]
Yes you can remove the code of the function. This can be recovered later if we need it again.

So only
```
(void)finger_down;
(void)evnt;
```
remains

**Comment by BlisterBoy** [comment]
The code has been removed :).

**Pull request merged**
