### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by fmatthew5876**
Compiles cleanly with gcc 8.3 and clang 8.0 with `-Wall -Wextra -Werror` on Ubuntu for me.

All except for a warning about unsigned `BGM_GetTicks()`. I didn't silence this warning yet as it indicates something we should actually revisit and maybe change this method to return something else.

### CODE REVIEW

**Comment by fmatthew5876** [comment]
I added some more warning fixes found in the jenkins builds. This is ready now.

**Comment by Ghabry** [comment]
Do you intend to also fix the warnings reported by MSVC?

**Comment by fmatthew5876** [comment]
Not at this time, fixing those would mean littering the code with casts, and that scares me. If you add a cast and then change the types later but forget to change the casts, the compiler won't warn you.

**Comment by Ghabry** [comment]
jenkins: test this please

**Comment by fmatthew5876** [comment]
Added some new warnings fixes from recent PR's that went in. Once this gets merged, we can do all future development with `-Wall -Werror` to avoid adding warnings to the code.

**Comment by fmatthew5876** [comment]
I added the 3ds build fix here

**Comment by fmatthew5876** [comment]
Rebased to fix warnings in latest PRs. Also found a regression in the message PR where wordwrap would be enable in 2k battles, even for old versions of the engine.

**Comment by fmatthew5876** [comment]
Removed it

**Pull request merged**
