### PR TITLE
(hopefully) Support frameskip and framelimiting for emscripten

### PR DESCRIPTION
**Pull request by Ghabry**
Can't test the frame limiting code because I have no 120 Hz display, the artificial test (commenting out Sleep() and running locally in a busy loop) works.

### CODE REVIEW

**Comment by fdelapena** [comment]
The [emscripten main loop test](https://github.com/kripken/emscripten/blob/950ebc6a19c66ef964f13deea1c59a2cf7955d76/tests/emscripten_main_loop.cpp) also mentions a 120Hz monitor may double FPS.

In that test there are interesting functions apparently not tried so far, like `emscripten_get_now`, `emscripten_get_main_loop_timing` and `emscripten_set_main_loop_timing`. The documentation says emscripten_set_main_loop_timing should be called after after `emscripten_set_main_loop` because emscripten_set_main_loop one overrides the value.

**Comment by carstene1ns** [comment]
Need to remove the debug code here and watch out for possible conflicts with the libretro PR.

**Comment by fdelapena** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
A promising solution for this is the new asynchify feature of the new LLVM emscripten backend.

https://emscripten.org/docs/porting/asyncify.html

By adding everything until Player::Update to ASYNCIFY_WHITELIST (is not that many, Player::Update is always close to the bottom of the stack) it should be possible to sleep normally.
(the old solution for this was the Emterpreter, but this was a custom bytecode interpreter that was very slow and threw errors when SDL events fired)

**Comment by Ghabry** [comment]
closing this, the new Asynchifier (see #1917) works perfectly

**Pull request closed without merging**
