### PR TITLE
Fix openOptionsMenu on Samsung devices

### LINKED ISSUE #536: Android: back button in button mapping activity not working in some devices
There is a comprehensive report by Inkuna in a [forum post](https://easy-rpg.org/forums/viewtopic.php?f=4&t=600) with Samsung :trollface: Galaxy Tab 4 and Android 5.0.2.

Seems like there is also a recent [comment](https://play.google.com/store/apps/details?id=org.easyrpg.player&hl=ru) in Google Play reporting the same issue. I could get device details from the Google Play developer console for this one if needed.

### PR DESCRIPTION
**Pull request by BlisterBoy**
Fixes #536 
It should work now :).

### CODE REVIEW

**Comment by BlisterBoy** [comment]
Sorry for the 19 days, that was just a little fix to copy/past !

**Comment by fdelapena** [comment]
Neat :) does it fix #536?

**Comment by BlisterBoy** [comment]
#536 ! Yep x).

**Comment by Ghabry** [comment]
I have no idea why your code works :D

**Comment by BlisterBoy** [comment]
Hahaha this is the solution given in the @fdelapena 's threads. It's a similar problem than for the previous Samsung's troll : we have to override an already implemented method to be sure that Samsung didn't modify their rom to cook a shitty code. I have absolutely no idea why they broke the Android API, maybe to promote a specific way to use their product (to use hardware button like in previous mantra ?). 
I have no Samsung device but I'm pretty sure this will work. At least it don't bring bug in normal android device.

Oh, thanks @fdelapena for the URLs !

**Pull request merged**
