### PR TITLE
Transition graphical fixes - MainLoop 4 of N

### PR DESCRIPTION
**Pull request by fmatthew5876**
Depends on #2050

Fix transition rendering

Fix: #1445
Fix: #1600
Fix: #1801 (both issues, + opacity issue in hh3 mentioned, + lufia glitch #1840 mentioned)
Fix: #1931
Fix: #1934
Fix: #1715

TBD: 
- [x] Retest issues after rebasing

### CODE REVIEW

**Comment by fmatthew5876** [comment]
@Br4ssman Please confirm this fixes #1931

**Comment by Br4ssman** [comment]
I tried to see the entire intro (skipping the first part, when the knights leave the castle and all that), but it gave me this error.

Captura


Then I edited the game and made a "jump to label" to see if this way I could check it and in principle it seems that it does it more correctly. As it goes with a lot of lag, I don't know if I'm viewing it correctly.

**Comment by fmatthew5876** [comment]
With a few more tweaks, this now passes all test cases of #1715

**Comment by fmatthew5876** [comment]
I've rebased this onto #2050 so that it no longer depends on the big main loop refactor.

**Comment by fmatthew5876** [comment]
Retested everything and it still works. This is ready.

**Comment by Ghabry** [comment]
Looks good to me. Will test the one before-boss transition (iirc it was in Eternal Legends? need to check) if it shows the correct scene now.

Frozen and black screen are gone now? This reduces the memory footprint again by 614 kbyte :+1:

**Comment by carstene1ns** [comment]
Will also do a final test and merge this evening.

**Pull request merged**
