### PR TITLE
Rpg2k3 v1.10

### PR DESCRIPTION
**Pull request by Ghabry**
Something unexpected happened: RPG2k3 v1.10 was released.
For now I detect the new engine version by testing for "ultimate_rt_eb.dll" in the game directory. I assume this version will diverge from the original RPG2k3 sooner or later...

Cherry said that he will implement ```ThisEvent``` in the next update. This fix is not breaking anything because RPG_RT was displaying an error when doing this.

TODO
* [x] Update RTP dict with new RTP files from official English translation

### CODE REVIEW

**Comment by fdelapena** [comment]
@Ghabry Are you doing the RTP dict update? I could do it and PR on your fork today.

**Comment by Ghabry** [comment]
I changed my mind. You can do it. Don't even have the japanese RTP here *g*

**Comment by fdelapena** [comment]
@Ghabry is this ready? works fine here and the RTP names part is merged already.

About the  172ed72 timer z-value change:  is this still required with the #466 fix?

**Comment by Ghabry** [comment]
@fdelapena Is still needed. Was just by luck that it worked before :D

**Pull request merged**
