### PR TITLE
Allow percent_sp feature for all 2k3 versions

### PR DESCRIPTION
**Pull request by fmatthew5876**
* Fix for all versions of 2k3
* Allow in 2k (if the chunk is present) as an EasyRPG extension

Fix: #1684 

Vote: Do we feel unsafe enabling this chunk for 2k games in EasyRPG?

### CODE REVIEW

**Comment by carstene1ns** [comment]
I guess if there is a game converted to 2k3, but shipped with RPG_RT from 2k, this breaks, since is ignored by RPG_RT. We have a workaround that prevents such things elsewhere, but not applicable here.
Chances are too minimal to care... (and likely other things are broken in battles too in this case)

**Comment by fmatthew5876** [comment]
In general, I'd like to be able to use these chunks in 2k games in the future.. But yes the situation you describe is potentially a break.

Still they'd have to convert the game, change sp cost to percentage style, and still keep the old RPG_RT to make this break.

Thats a pretty determined series of steps!

**Comment by carstene1ns** [comment]
> I'd like to be able to use these chunks in 2k games in the future.

This means either using a different editor (e.g. setting easyrpg mode anyway) or hacking stuff in. So not really detectable.

I feel more safe with this guarded, but as we both said, chances are low.

**Comment by fmatthew5876** [comment]
So I want these custom features for HH3, but I'm very far away from that. I've fixed this to use `Player::IsRPG2k3()` so we can just fix the bug for now.

Will revisit the customizations question at a later date with a more comprehensive plan. Maybe an ini setting for example?

**Pull request merged**
