### PR TITLE
Refactor Enemy AI

### PR DESCRIPTION
**Pull request by fmatthew5876**
~~Depends on: #2331~~
~~Depends on: #2380~~

Fix: #1831 

- [x] Configurable enemy AI algorithms
- [x] `RPG_RT` compatible algorithm
- [x] `RPG_RT+` compatible algorithm with bug fixes
- [x] Write full unit test suite
- [x] Manual play testing

### CODE REVIEW

**Comment by fmatthew5876** [comment]
I've written a full unit test suite and tested the code manually. This is ready for review

**Review by rueter37 — APPROVED** [review]

**Review by fdelapena — APPROVED** [review]

**Comment by fmatthew5876** [comment]
Proposal for next PR - custom chunks to enable per actor/enemy ai
----------------------

I wanted to run this proposal by you guys first before I started implementing. Basically I want to make actor and enemy ai configurable per actor / enemy.

1. Add a custom `actorai` chuck to `lcf::rpg::Actor`

| Value | Algo |
| -1 | Use System Default |
| 0 | RPG_RT |
| 1 | RPG_RT+ |
| 2 | ATTACK |

1. Add a custom `actorai` chuck to `lcf::rpg::SaveActor`

| Value | Algo |
| -1 | Use `Actor` value |
| >= 0 | Use specified algo |

2. Add a custom `enemyai` chunk to `lcf::rpg::Enemy`

| Value | Algo |
| -1 | Use System Default |
| 0 | RPG_RT |
| 1 | RPG_RT+ |

3. Add a `default_actorai` and `default_enemyai` chunk to the `lcf::rpg::System`

| Value | Algo |
| -1 | Use RPG_RT, or override with what user passes to `--actorai` / `--enemyai` command line args |
| >=0 | -1 in System means always use this and ignore the command line args, except in `--test-play` mode |


4. Refactor the actorai / enemyai factory to be array based, and preload the EasyRPG shipped algos into the arrays. Custom engines can add more of their own.


So this gives you maximum flexibility. For vanilla RPG_RT games, all the chunks are defaulted to RPG_RT and you can use the command line arguments. For games where the author really wants to use a specific algo, the command line arguments are no longer allowed to override the game authors wishes.

**Comment by Ghabry** [comment]
Your proposal sounds good to me. You can have decimal 200 for it in every object you listed.
Don't forget to prefix the options with ``easyrpg_`` to indicate that it is a custom chunk (I'm open for shorter prefixes or other ideas)

**Review by Ghabry — APPROVED** [review]

**Comment by rueter37** [comment]
I admit I'm late here, but I fully support the idea for using ID 200+ and the prefix `easyrpg_` for custom features.

**Pull request merged**
