### PR TITLE
Update splash logo image

### LINKED ISSUE #624: Use a better EasyRPG logo at startup
The EasyRPG logo at startup is good and should be kept, as it clearly brands the application.

However, there are some minor flaws:
- The colors of the text logo are too dark
- The URL does not contain the `s` for secure access and has an additional, unneeded slash `/` at the end

Here is the current logo (as everybody knows it :grinning:):
oldlogo
_I actually had to write an unxxd tool to extract it from source as-is._

And here is a quick mockup to address both issues:
mockup
Do not mind the realignment, it was for testing purposes. Also the font may be a bit too big in comparison.

About the URL: Maybe drop the `http://` or `https://` altogether?
**web: easy-rpg.org**
About the two logos: Maybe drop the text logo and just use a fullscreen logo?

Here is another mockup:
mockup2

### PR DESCRIPTION
**Pull request by fdelapena**
Here's a logo refresh proposed for 0.6.0 and later with dark background and more discreet.

Not using bright colours on purpose to keep eyes happy and integrate better with dark games.

Maybe the text looks a bit blurry, it might be sharpened up if worth.

Test: https://easyrpg.org/play/pr1463/

Closes #624, where there's the original SVG and if we go high res later or to make tweaks.

### CODE REVIEW

**Comment by Ghabry** [comment]
Imo the EasyRPG logo + text is too small, there is too much space wasted (huge borders left and right) and the font is hard to read, maybe make it a bit brighter?

**Comment by fdelapena** [comment]
The large margin perception is due to non 4:3 screens, for white background the white shows clearly the delimitation, this is a side effect. The margin is mostly the same, but also thinking for CRT overscan "safe areas", but not sure if worth nowadays, also game messages are probably not aware of this.

About brighter text, it may be increased a bit, but there is a risk of getting more attention than the logo itself. I could try sharpening the antialiased text.

**Comment by fdelapena** [comment]
I was using the original version, which is now the one for white backgrounds. Though the variant for dark backgrounds looks nice for the small web logo, the wave line looks low contrast in the "easy" part compared with the "RPG" part, also the "easy" part is maybe too bright compared with the last.

As commented on IRC, I'd vote for an unified logo tweak suitable for both light and dark backgrounds if possible, that would prevent possible misuse (like tentatively in this case).

Maybe thinking on a logo revamp (e.g. flat style for the nowadays hotness or some ideas from the Schoko variant) is worth for mid-future term.

**Comment by fdelapena** [comment]
Updated logo header with brighter version and added the PNG in the resources directory as requested.

**Pull request merged**
