### PR TITLE
Blisterboy's Android Studio import

### PR DESCRIPTION
**Pull request by carstene1ns**
Closes #850.

### CODE REVIEW

**Comment by carstene1ns** [comment]
jenkins: test this please

**Comment by carstene1ns** [comment]
jenkins: test this please

**Comment by Ghabry** [comment]
@BlisterBoy 
Your code is merged now ;). Happy Android coding, hehe.

**Comment by carstene1ns** [comment]
I have adapted the android build process on jenkins.
All builds since [394](https://easy-rpg.org/jenkins/job/player-android/394/) use gradle now.

**Pull request merged**
