### PR TITLE
Android : fix

### PR DESCRIPTION
**Pull request by BlisterBoy**
Fix for the problem @fdelapena found (i fixed another ui problem thinking it was the one he described).
The system should be bug free now

(NB : You can wait me to push the fix of setting UI before merging, maybe tomorrow)

### CODE REVIEW

**Comment by BlisterBoy** [comment]
Seriously Android foack you. I did a super optimized pattern etc. BUT in android you can't add a list view in a scrollview without having UX problem (the list is too short, no option to set the size).

BUT it's done.

**Comment by Ghabry** [comment]
Android...

Just a general note about git usage to avoid merge commits (from merging upstream/master):
You can use "git rebase upstream/master" to move your commits on the top of the upstream/master branch without generating extra commits.

In theory you can actually do this now, too. Just run the command and in the editor that opens (based on $EDITOR) remove the line "Merge https://...", then it should rebase on master with your merge commit deleted. (better backup your repo first) :D

**Comment by BlisterBoy** [comment]
Thanks for the explanation ! I confess I've stopped using the command line, I'm currently using the desktop app, do theses commits bother you ? If it's the case I'll restart to use the command line as you described :p.

**Comment by Ghabry** [comment]
Do you use the github desktop app? This one is very limited.

**Comment by BlisterBoy** [comment]
Oh it's fine, some recent updates brings a lot of cool features :p.

**Comment by BlisterBoy** [comment]
Buttons are now resizable from Settings.
It's WIP : I've got to centre buttons when they are displayed, to keep the same position when they are resized. And I have also to adapt the default layout.

**Comment by BlisterBoy** [comment]
Uuuurgh, center buttons is good for ux but brings somes practical problems (with default input layout). Nevereding problems between those two faces of GUI programming x). Btw I think I'm closing to the good balance.

**Comment by BlisterBoy** [comment]
The virtual button's letter is now centered, and proportional to the button. I was failing in math for so long haha.

**Comment by BlisterBoy** [comment]
Hmmmm I think it's good !
I think it's enough for this PR, I don't have the time to implement sliders in button mapping activity for butons' size, but I think the slider in Settings Activity is enough !

**Comment by BlisterBoy** [comment]
I moved the button_mapping file to internal memory, this will be easier to deal with changing working directory

**Comment by BlisterBoy** [comment]
Sooooo, calling an external application to choose a directory isn't a good option (can't specify directory choosing, random result depending on API and installed applications). I'll use an extern library.
It's like choosing a starter pokémon, I choose you Turhan's library : 
https://github.com/TurhanOz/ReactiveDirectoryChooser

I like his licence.

**Comment by Ghabry** [comment]
Okay, so two solutions now: Document that the library is required for Android (and ask the user to get it on it's own). Or copy paste the part from "ReactiveDirectoryChooser/library/src/main" into your project, if it isn't too much stuff. @fdelapena feedback?

Nice license :D

Pls note that I won't be able to test Android stuff this week because I'm on a business trip and the hotel only offers free WiFi for one device. That one device is my Laptop and not my Tablet :D

**Comment by fdelapena** [comment]
Well, adding it as an external dependency would need to set up repos in Jenkins, document and update all involved READMEs and wiki, project files (is maven ever used?). There are not much .java files, copying the whole src looks good to me for now, at least for a faster deployment, though the lib looks maintained.

BTW, Android 6 is coming :trollface:.

**Comment by BlisterBoy** [comment]
I can't wait the Samsung's version hahaha.
Btw no need to wait Android 6 to be trolled : I found that this lib (and all the other one) use the android support library. I have no idea how to add it in the project...

**Comment by BlisterBoy** [comment]
Pfuuu those android problems are boring. I'll study the possibility to create my own directory chooser : it's just a dialog with a list of directory name. If there is no futur problem (like permission or whatever) it shouldn't be difficult.
Btw this is enough for this PR :) ! I didn't encounter any problem :).

(Have a nice trip Ghabry ;p).

**Comment by Ghabry** [comment]
Thx and I can actually test it this evening... I can transfer it via USB :D

**Comment by BlisterBoy** [comment]
I did a directory chooser, that was very simple :B.
I'm finishing to implement the "changing directory" features. This won't be for this PR as it will necessitate some tests (system programming, yay).

**Pull request merged**
