### PR TITLE
0.5.4 regression fixes

### PR DESCRIPTION
**Pull request by Ghabry**
Fixes all known regressions in 0.5.4 for now plus the crash in OSX when enumerating a non-readable directory.

(The Android fix is not tested, abusing the PR builder to get a APK)

### CODE REVIEW

**Comment by Ghabry** [comment]
the "intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);" fix doesn't work :/

**Comment by Ghabry** [comment]
The lazy workaround works for me, can open K9 Mail with the files attached.
Please do tests on your devices @fdelapena @carstene1ns

**Comment by carstene1ns** [comment]
jenkins: test this please (need an APK for testing^^')

**Comment by carstene1ns** [comment]
The bug report option does work again on my samsung tablet. :+1:, but before merging let's push a fix for newlib based ports here and afterwards replace the google play apk.

**Pull request merged**
