### PR TITLE
Frozen Triggers Optimizations // Minor AsyncHandler Optimizations

### PR DESCRIPTION
**Pull request by fmatthew5876**
Depends on: #1896 #1897 

These are some player optimizations to fix some of the issues in #1883 

Debug build in master

Debug build after "Don't reallocate Sprite"

Debug build after "Add Player::GetTicks()"

Debug build after "Add AsyncFileRequest::BindStart()"

Debug build after "Don't update picture sprites after load"

These show improvements, but I still get 0 FPS so far.

### CODE REVIEW

**Comment by fmatthew5876** [comment]
Release build flame graphs

`master`




#1895 



These show improvements, but I still get 0 FPS so far.

**Comment by Ghabry** [comment]
Posting this here to prevent a conflict (or shall I PR it?): This won't fix Frozen Trigger but I noticed a problem when 0 FPS were reached:
https://github.com/EasyRPG/Player/compare/master...Ghabry:frameskip-fix?expand=1

When the Player runs at 0 FPS the next_frame will fall behind start_time which means the Player will continue running at 0 FPS even when the current screen could run faster.
next_frame and start_time are now properly reset when 0 FPS are reached.
For testing wait for ~10 sec in Frozen Triggers, then leave the screen to the left to enter the shop. With my patch the FPS go up to 60 again, in master it stays at 0 FPS for a long time until it recovers.

**Comment by fmatthew5876** [comment]
Go ahead and PR the 0 fps fix. I can always rebase onto you.

The stuff I am doing in here is experimental. Some of these fixes are quick hacks to prove bottlenecks and show where refactoring is needed.

For example one thing that is immediately clear is that we need to refactor the cache and async file code. When a file is already present in the cache we should aim for no memory allocations, no string copies, little to no hash lookups etc.. For games like this that code path has to be fast.

**Comment by Ghabry** [comment]
I have to test this with a WASM backend. Considering that all browsers that supproted asm.js support WASM there is no reason against using it. I just hope that this javascript function binding we use (e.g. for rmarchiv to get a cloud-based savegame system) still works as expected.

**Comment by Ghabry** [comment]
quickly hacked it together locally: Wow, this is muuuuch faster. I reach 45-55 FPS in Firefox and 55-60 FPS in Chromium.

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by Ghabry** [comment]
Okay emscripten builds now both (good for benchmarking):

WASM:
https://easyrpg.org/play/pr1895/?game=frozen_triggers&engine=rpg2k3e

asm.js:
https://easyrpg.org/play/pr1895/asmjs/?game=frozen_triggers&engine=rpg2k3e

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by Ghabry** [comment]
I disabled memory growth for asm.js and set a fixed limit of 500 MB. Wastes tons of RAM but gives a speedboost to ~35-40 FPS.
WASM still noticable faster.

**Comment by fmatthew5876** [comment]
This PR needs more work, and some of the fixes are hacks which need a more proper solution. If any of you guys are interested in working on this, don't worry about conflicting with this PR.

**Comment by fmatthew5876** [comment]
I've rebased this into just 2 small improvements to the async handler.

The picture stuff already went into. The ticks change will be part of the clock PR. Finally, the `BindStart()` feature I'm not sure I like and will rethink later.

So all that's left are 2 small improvements

**Pull request merged**
