### PR TITLE
Fix various minor problems

### PR DESCRIPTION
**Pull request by Ghabry**
Collection of stuff I encountered which doesnt fit in single PRs

The TurnToHero/AwayHero thing needs a test if this is RPG Maker behaviour (turn direction) but this fixes some sound spamming in #998 

Maybe keep this open for a while maybe I find something else :D

### CODE REVIEW

**Comment by Ghabry** [comment]
Todo list:
 - [ ] Fix broken tile in CLock of ATonement TV
 - [ ] Message boxes in UiD battle overlap the other battle windows (Regression >.<)

**Comment by carstene1ns** [comment]
Apropos battle and windows: did you notice at battle end (in düsterburg) you can see the background image duplicated beyond it when it is fading out/hidden?

**Comment by fdelapena** [comment]
> you can see the background image duplicated (...)

That issue seems to happen in all 2k game battles at least with these transitions, where backdrops are 320x160 and the window gets removed before the transition, which repaints the screen as pixel values change.

**Comment by Ghabry** [comment]
Proper fix for this would be: Keep the Messagebox open

**Comment by carstene1ns** [comment]
Also thought that, it would be the easiest at least.

**Comment by carstene1ns** [comment]
The music commit (2e441add9e90) has a bit of debug output left.

**Comment by Ghabry** [comment]
The last commit fixes the 1 HP problem in EHR and the 0 SP problem for Beta and Omega in OFF. ChangeClass command is still completely broken but at least the typical incorrect case (class applied on startup) is fixed.

**Comment by Ghabry** [comment]
Okay, I'm done here.

**Pull request merged**
