### PR TITLE
Creation of the Button Mapping System

### PR DESCRIPTION
**Pull request by BlisterBoy**
Hi guys !
I've implemented the button mapping system #438.
You can summon it in the Game Browser Activity. I had to change a lot of things but now we are abble to :
:+1: Change button disposition.
:+1: Add buttons.

It's kind basic for now, but I hope you'll like it !

### CODE REVIEW

**Comment by Zegeri** [comment]
It works like a charm. Thank you. :+1:
I think the F2 (toggle FPS) button is not needed, because you can already toggle the FPS display using the contextual menu. F5/Toggle zoom seems more fitting in the contextual menu too (or removed).

**Comment by Ghabry** [comment]
Awesome! Wohooo.
Busy today write yiu more in the èvening

**Comment by BlisterBoy** [comment]
I'm happy that you like it ^^, it took me the whole day yesterday but I learned a lot of things on Android (I was totally a nooby).
I focused on efficiency, the user experience doesn't satisfy me at 100% but I have a lot of college projects (EasyRPG is one of them) so I will improved the system when I will have the time in the next months : 
:mag: A "save on exit" context menu (for the moment you have to save before exit the activity).
:mag: The possibility to delete a button on a long-press touch
:mag: A zoom system for boutton.
:mag: Slightly extend the hitbox cross direction to improve the taking in hand.
:mag: The possibility to have several Button Mapping and associate one to a specific game

Zegeri I agree that those buttons will not be usefull for everyone but as we say in French "that doesn't eat bread" :p. It may be usefull for debugging purpose so for the moment I prefer not touch that.
But as you can see F2 and F5 are not operational, and the "*" button neither (which is more preoccupying), they are supported after API 11. I left a "//TODO" to remember that if we update the API.

**Comment by Zegeri** [comment]
What if we used an API 1 Keycode like KEYCODE_STAR for "*"?

**Comment by BlisterBoy** [comment]
Thanks Zegeri you make me found an issue : + / - * correspond to the KEYCODE_NUMPAD_... family, keycodes such as KEYCODE_STAR don't work.
I fixed the problem but it brings another one : KEYCODE_NUMPAD family are not supported until API 11, I don't really understand if we build the project on API 12 or 10 but it's maybe the good moment to migrate to API 12.

Less than 8% devices are under 12 and that number tends to quickly reduce since few month = https://developer.android.com/about/dashboards/index.html

I finally deleted F2 and F5 buttons as Zegeri suggested (I faced up the fact that my argumentary was just hiding laziness hahaha).

**Comment by BlisterBoy** [comment]
I fixed a minor bug and increased the virtual cross feeling, unless you found bugs I think I finished for this pull request :).

**Comment by Ghabry** [comment]
Instead of F2 or F11 it's probably better to show the purpose of the button

F2 - Toggle FPS (this one is really pretty useless)
F3 - Show log console. Nice to have
F9 - Show debug menu, only on map scene. Needs Debugmode, you can't toogle this mode under Android at the moment -> useless
F11 - Show save scene: Needs debugmode - same problem as above
F10 - Take screenshot -  Better as menu option
Ctrl left - When pressed: Walk through walls, disable random encounter -> Needs debug
F12 - Back to title (dangerous)

See the SDLActivity. Android provides functions to check the device API level

``
Build.VERSION.SDK_INT >= 12
``

__Before merging at least deleting of buttons would be useful.__

Nice to have:
Per game config -> Edit while game is running
"burger menu button" that toggles the  menu to make it more obvioua that there is functionality in the menu.
Per engine default (rpg2000 and 2003), engine detectable via jni callback to android.
Store button mapping in android settings file.
Rezisable buttons

**Comment by fdelapena** [comment]
For JNI we might differentiate between 2000 and 2000 Value too.

**Comment by BlisterBoy** [comment]
Huuum I don't know why I'm not able to detect a long press in the activity... For now it's possible to reset the mapping, I'll try latter.
The test on API version has been pushed.

As I told few posts before, I deleted Fx buttons :).

**Comment by Ghabry** [comment]
What do devs think about pushing this to play store soon
Users will be happy I guess.

**Comment by BlisterBoy** [comment]
I think so too :).
Vehicules was a huge improvement for the Player !

**Comment by fdelapena** [comment]
:+1: 
What about a global 0.3 early release after the Android build around April 1st?
With vehicles and maybe map loop, then fixes on 0.3.x for thr remaining major bugs

**Comment by Ghabry** [comment]
Okay lets wait another 1-2 weeks. GIves some more time for fixes...

**Pull request merged**
