### PR TITLE
Mention Font licenses in Readme file

### PR DESCRIPTION
**Pull request by Ghabry**
Also wenquanyi was updated to GPL2 or later with FE, before it was GPL2 only (problematic)

FmMidi link was 404

### CODE REVIEW

**Review by fdelapena — APPROVED** [review]
Nice to see the WQY license clarification :+1:!

It seems the fmmidi maintainer (Giuseppe Gatta aka nextvolume) does not announce modifications as copyright years in the readme, only mentions authorships for the fmmidi manual page, so looks okay keeping just the yuno copyright note.

**Comment by fdelapena** [comment]
It seems baekmuk is missing (#336).

**Comment by Ghabry** [comment]
looks MIT licensed, thanks!

**Comment by Ghabry** [comment]
this is not MIT but some custom license that looks OSI-compatible (basicly "copyright statement must stay").

There is no official URL anymore for Baekmuk, where shall I link to?

**Comment by fdelapena** [comment]
It seems https://kldp.net/baekmuk/ archived whatever it was in the downloads and wiki, now they host all contents in a packaged form, but downloads are still available.

**Review by carstene1ns — APPROVED** [review]

**Pull request merged**
