### PR TITLE
Clear system graphic when clearing the cache

### LINKED ISSUE #2601: Android: Improper cleanup of system graphic
When launching a 2nd game it will show a warning that the System graphic of the previous game was not found.

This looks harmless though, the 2nd game shows the correct graphic on the title screen.

Nothing serious but should be fixed

### PR DESCRIPTION
**Pull request by Ghabry**
Fix #2601

Bet this was omitted before due to some sideeffects but it seems to work by now.

(Not tested on Android yet though)

### CODE REVIEW

**Comment by Ghabry** [comment]
okay this made it worse on Android: Now it crashes when switching the game -_-

Good that we have working Android C++ debugging by now :)

**Comment by Ghabry** [comment]
Combined with the second commit it works but what worries me here is that I cannot figure out why it worked before o_O

**Comment by Ghabry** [comment]
Assert was not..... Triggered.

CMake defines NDEBUG.

All PR builds since the CMake migration were broken because they triggered the assert and nobody noticed😂

**Review by fdelapena — APPROVED** [review]

**Comment by carstene1ns** [comment]
> CMake defines NDEBUG.

Only in release mode. Pull request builds are in debug mode.

**Review by carstene1ns — APPROVED** [review]

**Pull request merged**
