### PR TITLE
Some font fixes/compatibility improvements

### PR DESCRIPTION
**Pull request by kakurasan**
I modified some glyphs for better look and MS font compatibility.
0 5 0-font-1 ---&gt; 0 5 0-font-1-patched
U+301C(〜) is rendered incorrectly, but I fixed it.
0 5 0-font-2 ---&gt; 0 5 0-font-2-patched

### CODE REVIEW

**Comment by carstene1ns** [comment]
This looks really good to me.

(For reference: This fixes a part of #514.)

**Comment by Ghabry** [comment]
thanks for your contribution

**Comment by rohkea** [comment]
This change makes European languages look worse. :(

The " is used both for closing and opening quotation marks. The correct rendering of opening quotation mark is “, and the correct closing quotation mark is ”. This change straight quotation mark (a compromise between “ and ”) with **closing** quotation marks (which is 100% incorrect).

Here’s how EasyRPG renders it now (two closing quotes):
screenshot_1

Here’s the correct rendering in RPG_RT (a straight quote that is a compromise between an opening and a closing quote):
correct-font

**Comment by kakurasan** [comment]
Here are screenshots on Japanese Windows (RPG_RT + "MS Gothic" font). U+0022 looks similar to "closing" quotation mark.

Seraphic Blue (Japanese) on Japanese Windows
Seraphic Blue (English) on Japanese Windows

Patch 1 (revert the change):
```diff
diff --git a/resources/shinonome/latin1/font_src.bit b/resources/shinonome/latin1/font_src.bit
index 0cece447..04d76585 100644
--- a/resources/shinonome/latin1/font_src.bit
+++ b/resources/shinonome/latin1/font_src.bit
@@ -683,10 +683,10 @@ DWIDTH 6 0
 BBX 6 12 0 -2
 BITMAP
 ......
-@@.@@.
-.@..@.
-.@..@.
-@..@..
+.@.@..
+.@.@..
+.@.@..
+......
 ......
 ......
 ......
diff --git a/src/shinonome_gothic.cpp b/src/shinonome_gothic.cpp
index 80ae8892..f43ddac9 100644
--- a/src/shinonome_gothic.cpp
+++ b/src/shinonome_gothic.cpp
@@ -35,7 +35,7 @@ ShinonomeGlyph const SHINONOME_GOTHIC[11219] = {
   { 31, false, { 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0 } },
   { 32, false, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
   { 33, false, { 0, 4, 4, 4, 4, 4, 4, 4, 0, 4, 0, 0 } },
-  { 34, false, { 0, 27, 18, 18, 9, 0, 0, 0, 0, 0, 0, 0 } },
+  { 34, false, { 0, 10, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0 } },
   { 35, false, { 0, 8, 10, 30, 11, 10, 10, 30, 11, 10, 2, 0 } },
   { 36, false, { 0, 4, 14, 21, 21, 6, 12, 20, 21, 14, 4, 0 } },
   { 37, false, { 0, 18, 21, 10, 8, 4, 4, 10, 22, 9, 1, 0 } },
```

Patch 2 (re-edit):

```diff
diff --git a/resources/shinonome/latin1/font_src.bit b/resources/shinonome/latin1/font_src.bit
index 0cece447..0a9ceb7c 100644
--- a/resources/shinonome/latin1/font_src.bit
+++ b/resources/shinonome/latin1/font_src.bit
@@ -683,7 +683,7 @@ DWIDTH 6 0
 BBX 6 12 0 -2
 BITMAP
 ......
-@@.@@.
+.@..@.
 .@..@.
 .@..@.
 @..@..
diff --git a/src/shinonome_gothic.cpp b/src/shinonome_gothic.cpp
index 80ae8892..a16960d6 100644
--- a/src/shinonome_gothic.cpp
+++ b/src/shinonome_gothic.cpp
@@ -35,7 +35,7 @@ ShinonomeGlyph const SHINONOME_GOTHIC[11219] = {
   { 31, false, { 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0 } },
   { 32, false, { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 } },
   { 33, false, { 0, 4, 4, 4, 4, 4, 4, 4, 0, 4, 0, 0 } },
-  { 34, false, { 0, 27, 18, 18, 9, 0, 0, 0, 0, 0, 0, 0 } },
+  { 34, false, { 0, 18, 18, 18, 9, 0, 0, 0, 0, 0, 0, 0 } },
   { 35, false, { 0, 8, 10, 30, 11, 10, 10, 30, 11, 10, 2, 0 } },
   { 36, false, { 0, 4, 14, 21, 21, 6, 12, 20, 21, 14, 4, 0 } },
   { 37, false, { 0, 18, 21, 10, 8, 4, 4, 10, 22, 9, 1, 0 } },
```

I prefer "Patch 2" because of MS Gothic (Japanese) font.

Seraphic Blue (Japanese) / Patch 2
Seraphic Blue (English) / Patch 2

I'm not sure which is better.

**Comment by rohkea** [comment]
I think the solution is to use different fonts for Japanese and European translations.

The " character can be fixed, but … would look weird either for Japanese or for European lanuages. For Japanese, … should be in the middle of the line. For European languages, it should be on the bottom.

I will add the code for using different fonts in the evening.

**Comment by fdelapena** [comment]
In my opinion, sometimes Shift_JIS to Unicode mappings are not perfect, e.g. well known issues with the inverted wave dash, or Yen in the codepoint of backslash. For the Yen sign  issue (also an issue for Won sign in Korean codepage) they could be solved by doing a replacement directly in text parsing. For other stuff (wave dash in top or middle, quotes styling, etc.) might use the same solution depending on the used game encoding.

**Comment by Ghabry** [comment]
I also know one european user who doesn't like the ... formatting of Shinonome. The 3 dots are centered, not at the bottom.

**Pull request merged**
