### PR TITLE
Some minor changes on layout and a function

### PR DESCRIPTION
**Pull request by sushi24**
Hi! 
With Souigetsu (or kael as you prefer) we saw some little improvements to do. It's not a big deal, it's only a way to avoid the redundancy in the code! Hope it could be helpful ^^' 
We also reduce a function's test.

### CODE REVIEW

**Comment by carstene1ns** [comment]
Hello, thanks for the Pull Request. It seems you accidentally included unrelated changes (the audio stuff) which we already have present in the repository.
Can you please update your branch and apply the changes on the current master branch to fix this? Thanks!

https://help.github.com/articles/syncing-a-fork/

If you need help feel free to ask.

**Comment by sushi24** [comment]
For the audio stuff, i've just add a space accidentally i didn't change anything on it ^^

**Comment by carstene1ns** [comment]
Well, i tell you what your git log looks like:
- You forked the repository and have all changes until March 16 in it.
- Then you committed you changes today.

In the meantime you manually included the android related changes (→ the audio stuff) either by manually copying it or whatever in your local checkout.
Now we have the problem.

**Comment by sushi24** [comment]
Oh ok sorry i'm beginning with this kind of stuff, so i'll try to correct this as soon as i can!

**Comment by Ghabry** [comment]
We have time :)

**Pull request closed without merging**
