### PR TITLE
RPG_RT v1.11 fixes

### PR DESCRIPTION
**Pull request by fmatthew5876**
Fix: #587

### CODE REVIEW

**Comment by Ghabry** [comment]
Imo there is no reason to disable saving in a debug menu. When saving at the wrong location this is the fault of the user. Maybe allow saving but show a message in a WindowHelp when Save is hovered? ("Saving here can corrupt the save!" or some other wording)

Opinions?

**Comment by fmatthew5876** [comment]
This is the only case I know of where it's not good to save. As far as I can tell the side effect is only visual. When you load the game the screen will no longer be erased but everything else should play out the same way. Even transition in effects will consume the same number of frames.

So if we think it's better to just allow people to save in all cases, ( I can see the argument from a debugging point of view) I can just remove the commit.

**Comment by carstene1ns** [comment]
I have no strong opinion here, but I guess debug save should always be possible.

**Comment by fmatthew5876** [comment]
Ok I removed the debug save thing and rebased. Now this is the just the RPG_RT 1.11 message box fix.

**Pull request merged**
