### PR TITLE
0.4.1

### PR DESCRIPTION
**Pull request by fdelapena**

### CODE REVIEW

**Comment by fdelapena** [comment]
@tomyun 0.4.1 has been tagged. Note: there would be changes in the `easyrpg-player -v` output

**Comment by tomyun** [comment]
@fdelapena seems like `src/version.h` didn't get version change. `easyrpg-player -v` still shows 0.4.0.

**Comment by carstene1ns** [comment]
facepalm
Yes, seems like it.
Okay, let's fix this and move the tag. Requires updates to my Arch package and the ones on OBS, but is better than having 0.4.2 with no functional change.

**Comment by Ghabry** [comment]
@tomyun 
The 0.4.1 tag was moved and all packages in our download section updated :).
Should be fine now.

**Comment by tomyun** [comment]
Sounds good. Updates submitted for homebrew-games:
- liblcf: Homebrew/homebrew-games#522
- easyrpg-player: Homebrew/homebrew-games#523

**Comment by fdelapena** [comment]
Thank you tomyun for the update :)

Sorry for the noise, the missing version.h file update is my bad, it is a new one and the classic search for the version bump didn't find "0.4.0" in it.

**Pull request merged**
