### PR TITLE
Speedup Startup + RTP detection

### PR DESCRIPTION
**Pull request by Ghabry**
Two improvements:

- The RTP is now initialized the first time a file is missing. This way there is no startup delay, instead the delay is now when the first RTP asset is requested. Yes this only moves the problem but for some games this means 0 delay.
- lcf INI parser replaced with a simple parser that just reads all lines and skips until the Key/Value pair is found. No extra caching, that's why I don't consider this a fix for #1903, likely can be improved more.

### CODE REVIEW

**Comment by fmatthew5876** [comment]
> Delay the RTP detection until a file is missing.

How long does it take to do this routine the first time? 

I'm not sure I like this approach because it'll cause random stutter in the middle of game play the first time an asset is missing. That could be very jarring for the player.

Many games which don't use rtp still have missing assets. It's very common, and all those games will still pay the cost of initializing rtp.

I'd rather just pay the cost up front and deterministically, than have a random slowdown occur during game player.

> Registry Wine: Use custom INI parser (faster)

This looks like a step in the right direction. Ultimately we could just refactor it further to be most optimal. 

* Keep a set of all the keys we'll ever need in some array, tag each one with an enum. 
* Change `Registry` to an object, in it's constructor read the file and load the full set of keys once into an array of string values.
* Provide get methods to just return the key values by enum as an index into the array.

The result would be exactly one time reading the registry file and simple array indexing to retrieve values.

**Comment by Ghabry** [comment]
thanks for the feedback. Will work on a better solution.

When the RTP detect is fast enough there is no reason to use the "delay rtp detection" code.

**Comment by fmatthew5876** [comment]
With the delays added in #1940, maybe there is a possibility to use them to our advantage.

In most cases, I would expect the title screen, system graphic, and title music to be included in the game assets and not be RTP. The face graphics in the load game menu are likely to be custom for most serious games also.

Given that, how about we do this:

1. Load all assets needed for title and load screen only. 
    * If none of them in RTP, skip RTP detection. 
    * If any are RTP, then we have to wait for RTP detection on startup.
2. Upon loading the title screen, immediately kick off a background thread to start detecting RTP. 
3. Once we new game / load game and wait for transition out and the 1 second delay, block on black screen if RTP detection still hasn't finished.

With this approach we could achieve parallel and deterministic loading of RTP.

**Comment by fmatthew5876** [comment]
Can we push back the "delay rtp detection" piece to a follow up PR? The custom parser your wrote for wine results in a significant speedup and should go in sooner

Master
```
--------------------------------------------------                                                                                                                           
Benchmark           Time           CPU Iterations                                  
--------------------------------------------------                                                                                                                           
BM_InitRtp   31469504 ns   31464948 ns         22   
```

With new parser
```
--------------------------------------------------                                                                                                                            
Benchmark           Time           CPU Iterations                                                                                                                             
--------------------------------------------------                                                                                                                            
BM_InitRtp    5514361 ns    5512936 ns        137  
```

**Comment by Ghabry** [comment]
Using a Lowercase func that works in-place gives a 25% speedup and completely removing the Lowercasing (incompatible with Windows registry behaviour) gives another 75% speedup.

```
With normal LowerCase:
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_InitRtp   38521503 ns     38474798 ns           18

With in-place Lowercase func
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_InitRtp   25587533 ns     25436706 ns           27

Without Lowercase:
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_InitRtp    7270756 ns      7258756 ns           95
```

**Comment by carstene1ns** [comment]
The last commit "lowercasing all in place" is wrong.
You lowercase the actual path. Also, you do it twice.

```
Debug: RTP path c:\\users\\carsten\\application data\\kadokawa\\common\\rpg maker 2003 rtp is invalid, not adding
```

```ini
[Software\\Wow6432Node\\KADOKAWA\\rpg2003] 1576949727
#time=1d5b82508a24236
"RuntimePackagePath"="C:\\users\\carsten\\Application Data\\KADOKAWA\\Common\\RPG Maker 2003 RTP"

```

**Comment by Ghabry** [comment]
ups. Removed the in-place lowercasing when inside of the section, thx. Won't hurt the parsing speed much as the section-searching is the slow part.

**Pull request merged**
