### PR TITLE
Translation enhancements

### LINKED ISSUE #2691: Reloading translations crashes
Translating works by rewriting the database strings, so after one translation you must reload the database.

The reloads causes danglings pointers everywhere into the old database.

Needs some callback feature across the scene stack, e.g. ``OnTranslationChange`` that refreshes all pointers :/

### PR DESCRIPTION
**Pull request by Ghabry**
Also do not unload the system graphic string anymore here.

Fix #2691

~~Waiting for Jan (Deep8) to confirm that this is working as translation change on map is not something that is normally possible :)~~

https://user-images.githubusercontent.com/1331889/154381192-1fa4377d-5417-4e2c-99a2-56dc09c5ed30.mp4

### CODE REVIEW

**Comment by fdelapena** [comment]
jenkins: test this please

**Comment by rueter37** [comment]
While testing this PR I unfortunately still get a crash when I change the translation, switch back to the default language and start a new game.

**Comment by Ghabry** [comment]
@rueter37
I cannot reproduce this. Guess you hit some edge case.
Can you provide a sample game?

**Comment by rueter37** [comment]
Try this one: [TestGame-2000.zip](https://github.com/EasyRPG/Player/files/8083405/TestGame-2000.zip). This is a modified version of TestGame-2000 which contains a small german translation which translates some strings in the starting map to German.

**Comment by Ghabry** [comment]
@rueter37  found what you meant. Happened after resetting the game and then switching the translation. Fixed now.

Also added translation support for the web player. Though the asset translating is limited to "only once per asset" so if you e.g. loaded already the original (like the Title graphic) it is not replaced anymore.

**Comment by Ghabry** [comment]
well who cares about API limitations.
Only had to remove an assert that triggers a false-positive after the request clear.

The only thing that is not replaced is the system graphic but this should be acceptable ^^

**Comment by rueter37** [comment]
Tested it again and the crash on starting a new game after switching the language back to default no longer occurs. :+1:

**Comment by Ghabry** [comment]
(now I'm done)

**Review by fdelapena — APPROVED** [review]

**Comment by lychees** [comment]
Most of the localization games contains not only texts, but also images. (e.g. the mannual in yumenikki)
Do we have a plan to support this feature in the future?

image
image

**Comment by rueter37** [comment]
@lychees As far as I know this is already supported. According to the [manual](https://easyrpg.org/player/guide/game_translation) it should work like this:

> **Translating assets**
> 
> Many games also contain text on graphics, and a few even have voiceover.
> These assets can also be translated. All you have to do is mirror the corresponding path in the translation folder.
> For example, the translated version of Picture/Intro.png is located in languages/LANGUAGE_NAME/Picture/Intro.png.

**Comment by lychees** [comment]
Thanks, that would be helpful.

**Pull request merged**
