### PR TITLE
Fix off-screen panning

### LINKED ISSUE #1169: ChipSet and Battle positioning issues
#### Attach files (as a .zip archive or link them)
[TestEasyRPG.zip](https://github.com/EasyRPG/Player/files/1009210/TestEasyRPG.zip)

#### Describe the issue in detail and how to reproduce it:
Hi, our main coder prepared a mini-demo of two problems we are experiencing in Easy RPG only. The issues are:

1) ChipSet: in the map there is a column with a hole inside. The column appears withuot holes in RPG Maker. The hero of the mini-demo will show you the bugged column (which is part of a ChipSet) while you play it;

2) Battle positioning: in our game we implemented a FaceSet Animation System. We don't use static FaceSets but we do use Battle animations to see them moving (mouth, eyes, etc). In the mini-demo the hero will talk for the first time and the animated FaceSet will appear in the right position (in its box of our text message picture). Then if you walk to the right, after the column, the game will take control of the hero, change the camera displacement and then move the hero upwards. He will talk again and this time the animated Battle of the FaceSet will not appear in the box. THIS DOES NOT HAPPEN IN RPG MAKER. To show the animated Battle of the FaceSet, throughout our game we use Event 0001 of every map as its target. Of course this event need to be repositioned every time we open a new message box, expecially in big maps, in order to see the animation played inside the box. This repositioning is performed by a parallel process (Common Event number 894, you find it in the test case). In RPG Maker this algorith always work, in any map and in any condition. In Easy RPG the result of the calculation is wrong because the Battle appears in different, wrong, positions (not in the message box). We are experiencing this problem in big maps, the ones which left the DEBUG message "Image size out of the boundary" in the Easy RPG log.

Please check the mini-demo and let us know where the differences with RPG Maker are and if you can fix them.
Thank you!

### PR DESCRIPTION
**Pull request by scurest**
I think this is ready....

Keep track of how much we've actually panned so we know not to go past where the pan should be.

Should fix #1169. It don't think it fixes _any_ other panning problems though. Matching RPG_RT turned out to be a nightmare -_-;;

I needed a non-negative mod function. Ghabry added a proper one in 59b4b54, so the `mod` function I added should be changed to use that whenever both of them make in into master.

### CODE REVIEW

**Comment by Ghabry** [comment]
The incorrect screen pan offset in the Razas intro is fixed, too 👍

**Comment by carstene1ns** [comment]
Sooo, any possible candidates for regressions? (´▽`)

**Comment by scurest** [comment]
Heh :) I wanted to check I didn't regress 342351d4, but I don't think I understand the bug it fixed, since characters seem to die when they hit the bottom of the screen whether the `+2`s are there or not?

**Comment by Ghabry** [comment]
That +2 was added because in easyrpg the screen position was wrong by 2 pixels after walking around compared to RPGRT.
When GetScreenX and GetScreenY yield the same result as RPG_RT without the +2 and the viewport loooks correct it should be safe to remove it.

**Comment by carstene1ns** [comment]
Well, I wanted to wait until the the `+2` and `mod()` stuff is changed before merging this.
We need to remember this before preparing 0.5.2.

**Comment by Ghabry** [comment]
oh, right. Sorry. :/

**Comment by Ghabry** [comment]
mod() is done in my PR. +2 not

**Pull request merged**
