### PR TITLE
Emscripten bugfixes

### PR DESCRIPTION
**Pull request by Ghabry**
- Regression fix: Path was not made canonical anymore
- Replace regex with a replace function

### CODE REVIEW

**Comment by Ghabry** [comment]
marking as draft, this doesnt fix anything :sweat_smile:

**Comment by Ghabry** [comment]
oh my bad, pushed to the wrong branch :sweat_smile:

**Comment by Ghabry** [comment]
Finally ready for review :tada:

**Review by fdelapena — APPROVED** [review]

**Review by carstene1ns — APPROVED** [review]
Looks good to me.

**Review by fmatthew5876 — APPROVED** [review]

**Pull request merged**
