### PR TITLE
Fix EHR & Desolate city cutscene (issue 1226)

### PR DESCRIPTION
**Pull request by Ghabry**
See commit message

Tested with: Nobihazard 2, Material Game and DirectionTest (see #1020)

### CODE REVIEW

**Comment by carstene1ns** [comment]
Just saying, #1120 is unrelated...

**Comment by Ghabry** [comment]
Can anybody test if this fixes Desolate City?

**Comment by Ghabry** [comment]
Added fix for Desolate City

**Comment by Ghabry** [comment]
#1198 could be related

**Pull request merged**
