### PR TITLE
Emscripten playground

### PR DESCRIPTION
**Pull request by fdelapena**
Trying to play it at https://easy-rpg.org/jenkins/job/player-js-pr/ws/easyrpg-player.html

### CODE REVIEW

**Comment by fdelapena** [comment]
jenkins test this please

**Comment by fdelapena** [comment]
PR builder works again:
https://easy-rpg.org/jenkins/job/player-js-pr/ws/easyrpg-player.html

Currenty shows this exception message:
```Uncaught exception: 0```

Maybe exit(1) throws this. Looks promising.

**Comment by Ghabry** [comment]
Actually it seems to work except the rendering. When you press enter you can see that it writes "Warning: No start position" in the Javascript console which indicates that Scene::Title is active.

**Comment by fdelapena** [comment]
I haven't checked Player code but SDL emscripten tests use 32 bit sw surface for screen and SDL_flip. Maybe requires some guards. By the way, they changed EMSCRIPTEN to __EMSCRIPTEN__.

**Comment by fdelapena** [comment]
Maybe getting files from https://github.com/EasyRPG/TestGame/ (or the desired game) and putting them from the Jenkins job is better for fetching from the same domain (preventing CORS issues).

The function requires 2 parameters and looks like the 1st and 2nd could be the same if placed in the same relative path, the first the real file system and the second the virtual file system If I understand the documentation correctly.

**Comment by Ghabry** [comment]
This port would need a refactoring of the code because the file loading must be asyncronous. I don't see a reason for downloading everything at the beginning, most files are never used anyway during one play session (and music can be huge).
This basicly means:
No file can be used directly after it was requested (e.g. via a Cache::-function). Instead you have to deal for one frame without the file. Then it returns to the main loop where you pause the main loop until all download requests are finished. And on the 2nd frame you can finally work with the file.
(Of course loading can be still done syncrhonous on other systems, but the code should be async-friendly)

**Comment by Ghabry** [comment]
Jenkins, retest this please <3

**Comment by Ghabry** [comment]
Jenkins, retest this please <3

**Comment by Ghabry** [comment]
Jenkins, retest this please <3

**Comment by Ghabry** [comment]
Jenkins, retest this please <3

**Comment by Ghabry** [comment]
Jenkins retest this please <3

**Comment by Ghabry** [comment]
This is ready for now... Audio doesn't work and FPS are not really 60...

**Pull request merged**
