### PR TITLE
Fix interpreter problems in smashbros, Doraemon 2,  特に理由 and Win' Wind' Windy'

### PR DESCRIPTION
**Pull request by Ghabry**
Visual demonstration of the off-by-two:
https://easyrpg.org/play/master/?test-play&start-position=8%201&new-game

Fixed:
https://easyrpg.org/play/pr1020/?test-play&start-position=8%201&new-game

Hold STRG (for walk everywhere) and one tile to the right. You will notice a minor scroll of two pixel which doesn't happen anymore in my PR.

And smash bros: https://easy-rpg.org/play/master/?game=smashbros

Fixed: https://easy-rpg.org/play/pr1020/?game=smashbros

Try to fall out of the bottom of the arena.

**The 2nd commit** "Don't change direction when"... has a test case here: 
[Project5.zip](https://github.com/EasyRPG/Player/files/443094/Project5.zip)

Online master: https://easyrpg.org/play/master/?game=issue_1020

Online fixed: https://easyrpg.org/play/pr1020/?game=issue_1020

In the old player the girl will always revert to bottom look instead of keeping the changed one. I found this while trying to fix Doraemon, but is unrelated.

The **3rd commit** removed these IsMoving checks and I have no idea what the side-effect of this is but **it fixes Doraemon 2 shooting.** Maybe @Zegeri has an idea. I couldn't find any regression yet but only played for a few minutes.

Online master: https://easyrpg.org/play/master/?game=nobihazard2

Online fixed: https://easyrpg.org/play/pr1020/?game=nobihazard2

Skip the intro by choosing always the bottom option when asked a question, then wait until the zombie goes through the door. Pick up the pistole, equip it in the menu, press SHIFT and shoot with enter.

### CODE REVIEW

**Comment by Zegeri** [comment]
About the third commit: it breaks the Move Forward command after a page change. Example:
[TestDirection.zip](https://github.com/EasyRPG/Player/files/444863/TestDirection.zip)
The monster should walk to the right, but after the removal of the SetDirection, the event moves downwards.

**Comment by Ghabry** [comment]
Thanks. Then the 3rd commit is obviously wrong and the problem is something else.
Will try to isolate that nobihaza2 problem when I find some time... will take a few hours I guess >.>

All this stuff in this thread is excellent for event unit testing... I really have to finish this.

**Comment by Ghabry** [comment]
@Zegeri 
This one fixes your testcase and nobihazard 2 for me

**Comment by carstene1ns** [comment]
Too lazy to compile it myself:
jenkins: test this please :)

**Comment by Zegeri** [comment]
Looks good to me.

**Pull request merged**
