### PR TITLE
Implement asynchronous vehicle teleports + Bgm fixes + Choice fix

### PR DESCRIPTION
**Pull request by fmatthew5876**
~~Depends on #2041~~

Fix: #2043 
Fix: #1864 
Fix: #1641 
Fix: #1778 
Fix: #2048

### CODE REVIEW

**Comment by Ghabry** [comment]
I will test this now with the latest version o fyume2kki, maybe they broke it again xD

**Comment by Ghabry** [comment]
#2049 is not fixed by this but where would be the fun if Yume2kki would fully work ;)

**Comment by Ghabry** [comment]
Jenkins: Test this please

I removed the "cp .... wast" line. Must be a left over from my emscripten test from September, the file does not exist anymore.

**Comment by fmatthew5876** [comment]
Added the fix for #2048

**Pull request merged**
