### PR TITLE
Gohufont for latins, Vietnamese support

### PR DESCRIPTION
**Pull request by toaranotdev**
Likely still have some bugs, but latin-ext-a looks fine to me. I've gave the font to people and It's been a few days, no one seems to have complained about the font so yeet

- Shinonome was edited, I left ttyp0 untouched
- Was designed with Japanese games (sorry can't say that word) in mind, thus Shinonome was edited
- Glyphs were changed / added: 
á à ả ạ ã
ấ ầ ẩ ậ ẫ
ắ ằ ẳ ặ ẵ
í ì ỉ ị ĩ
é è ẻ ẹ ẽ
ế ề ể ệ ễ
ố ồ ổ ộ ỗ
ú ù ủ ụ ũ
ứ ừ ử ự ữ
... And their capitalized forms
- ttyp0 glyphs fall back basically doesn't exist, which is the one that needs to work as it has vietnamese glyphs

### CODE REVIEW

**Comment by fdelapena** [comment]
jenkins: ok to test

**Comment by Ghabry** [comment]
@toaranotdev 

Can you provide a testgame where I can see the font in action?

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by Ghabry** [comment]
I do not really understand what this PR changes? I have no idea which glyphs are used by Vietnamese so I just grabbed the one from VISCII https://en.wikipedia.org/wiki/VISCII

Top is normal player, below is with your font. So this already works?!

**Did I miss any glyphs?**

Screenshot_20220106_182249-fs8

**Comment by toaranotdev** [comment]
> @toaranotdev
> 
> Can you provide a testgame where I can see the font in action?

https://www.mediafire.com/file/b17p0ggr30d6qjc/nobita-hazard.zip/file

**Pull request closed without merging**
