### PR TITLE
Add more custom game settings in the database

### PR DESCRIPTION
**Pull request by rueter37**
This PR adds the following game settings which can be set in the game database:

- BattleCommands: Disable RPG Maker 2003 row feature
- Actors: Protected against critical hits
- Actors: Increased physical attack evasion rate
- Actors: Immune to attribute downshifts
- Actors: Ignore enemy evasion on physical attacks
- Actors: Unarmed attack hit rate
- Actors: States inflicted by unarmed normal attacks
- Actors: State infliction probability by unarmed normal attacks
- Actors: Attributes used by unarmed normal attacks
- Actors: Unarmed attack dual attack
- Actors: Unarmed attack targets entire enemy party
- Enemies: Protected against critical hits
- Enemies: Increased physical attack evasion rate
- Enemies: Immune to attribute downshifts
- Enemies: Ignore enemy evasion on physical attacks
- Enemies: Normal attack hit rate
- Enemies: States inflicted by normal attacks
- Enemies: State infliction probability by normal attacks
- Enemies: Attributes used by normal attacks
- Enemies: Quarter instead of half damage on defend action
- Enemies: Normal attack targets entire player party
- Skills: Affected by avoid attack states
- Skills: Critical hit rate percentage
- Skills: Affected by row modifiers
- Skills: Skill HP cost type
- Skills: Skill HP cost in percent of the maximum HP
- Skills: Skill fixed value HP cost
- States: Clear certain states on infliction by this state
- Terrains: Damage in percent of the actor HP
- Terrains: Damage can kill the actor
- System: Use RPG Maker 2000 battle system in RPG Maker 2003 games
- System: Use RPG2kE strings in RPG Maker 2000 battles in RPG Maker 2003 games

### CODE REVIEW

**Comment by Ghabry** [comment]
Legend:

:+1: - Accepted without changes
:ok: - Accepted with changes
:question: - Question for PR author
:hourglass: - Pending review work on my side
:no_entry: - Rejected

- [ ] :question: Allow skill hit rate to be dependent of the actor or enemy **I do not really understand this one? Feels a bit dirty**
- [x] :ok: BattleCommands: Disable RPG Maker 2003 row feature
- [ ] :hourglass: Actors & Enemis: Custom Actor AI behavior
- [x] :+1: Actors & Enemies: Protected against critical hits.
- [x] :+1: Actors & Enemies: Increased physical attack evasion rate
- [x] :+1: Actors & Enemies: Immune to attribute downshifts
- [x] :+1: Actors & Enemies: Ignore enemy evasion on physical attacks
- [x] :+1: Actors & Enemies: Unarmed/Normal attack hit rate
- [ ] :hourglass: Actors & Enemies: States inflicted by unarmed normal attacks. **OK but needs code review**
- [ ] :hourglass: Actors & Enemies: State infliction probability by unarmed normal attacks. **OK but needs code review**
- [ ] :hourglass: Actors & Enemies: Attributes used by unarmed normal attacks. **OK but needs code review**
- [x] :+1: Actors: Unarmed attack dual attack
- [x] :+1: Actors & Enemies: Unarmed attack targets entire party
- [x] :+1: Enemies: Quarter instead of half damage on defend action
- [ ] :question: Skills: Affected by avoid attack states. **Minor: I dislike the name of the field. Any better idea?**
- [x] :+1: Skills: Critical hit rate percentage
- [ ] :hourglass: Skills: Affected by row modifiers
- [x] :+1: Skills: Skill HP cost type
- [x] :+1: Skills: Skill HP cost in percent of the maximum HP
- [x] :+1: Skills: Skill fixed value HP cost
- [ ] :question: States: Clear certain states on infliction by this state. **Minor: Maybe call it ``easyrpg_immune_states``. How does this interact with equipment states inflicted by e.g. cursed armor?**.
- [x] :+1: Terrains: Damage in percent of the actor HP
- [x] :+1: Terrains: Damage can kill the actor
- [x] :ok: System: Use RPG Maker 2000 battle system in RPG Maker 2003 games.
- [x] :ok: System: Use RPG2kE strings in RPG Maker 2000 battles in RPG Maker 2003 games.
- [ ] :hourglass: System: Use RPG Maker 2000 battle commands in RPG Maker 2003 games
- [ ] :hourglass: System: Default autobattle AI
- [ ] :hourglass: System: Default enemy AI

**Comment by Ghabry** [comment]
@rueter37 

Is it possible with not-too-many rebase pain to move the following commits in more PRs? The liblcf chunks can stay!

One new PR for:
- All AI related commits

One new PR for:
- Support RPG Maker 2003 battle commands in RPG Maker 2000 battles

**Comment by rueter37** [comment]
"Allow skill hit rate to be dependent of the actor or enemy" means that the hit rate of the skill is equivalent to the unarmed hit rate of the actor or enemy or the hit rate of the equipment of the actor. This is useful for making skills which act similar to normal attacks.

**Comment by rueter37** [comment]
About "States: Clear certain states on infliction by this state": Cursed armor blocks the removal of a state.

**Comment by rueter37** [comment]
Did the requested PR changes now.

**Comment by rueter37** [comment]
Sadly I haven't got a better name idea for "Skills: Affected by avoid attack states".

**Comment by rueter37** [comment]
@Ghabry: I have some suggestions:
- Change the check for "Allow skill hit rate to be dependent of the actor or enemy" to -1 instead of every negative value
- Change `easyrpg_affected_by_avoid_attacks` to `easyrpg_affected_by_evade_all_physical_attacks`
- Change `easyrpg_clear_states` to `easyrpg_immune_states` (your suggestion)

If you think the suggestions are okay, then I will update [liblcf#433](https://github.com/EasyRPG/liblcf/pull/433) and this PR accordingly.

**Comment by Ghabry** [comment]
@rueter37  sorry guess I was too stressed and missed your comment: Yeah these suggestions are fine! Please apply them.

**Comment by Ghabry** [comment]
@rueter37 

Patch for

- Actors & Enemies: States inflicted by unarmed normal attacks.
- Actors & Enemies: State infliction probability by unarmed normal attacks.

(You have this as a combined commit)

Reduced code duplication with a lambda:

```cpp
---
 src/game_battlealgorithm.cpp | 59 ++++++++++++++----------------------
 1 file changed, 23 insertions(+), 36 deletions(-)

diff --git a/src/game_battlealgorithm.cpp b/src/game_battlealgorithm.cpp
index 570979374..3c939b64e 100644
--- a/src/game_battlealgorithm.cpp
+++ b/src/game_battlealgorithm.cpp
@@ -655,6 +655,27 @@ bool Game_BattleAlgorithm::Normal::vExecute() {
 	// Conditions healed by physical attack:
 	BattlePhysicalStateHeal(100, target_states, target_perm_states);
 
+	auto easyrpg_state_set = [&](const auto& state_set, const auto& state_chance) {
+		int num_states = static_cast<int>(state_set.size());
+		for (int i = 0; i < num_states; ++i) {
+			int inflict_pct = 0;
+			if (i < static_cast<int>(num_states) && state_set[i]) {
+				inflict_pct = static_cast<int>(state_chance);
+			}
+			auto state_id = (i + 1);
+
+			if (inflict_pct > 0) {
+				inflict_pct = inflict_pct * target.GetStateProbability(state_id) / 100;
+				if (Rand::PercentChance(inflict_pct)) {
+					if (!State::Has(state_id, target_states) && State::Add(state_id, target_states, target_perm_states, true)) {
+						AddAffectedState(StateEffect{state_id, StateEffect::Inflicted});
+					}
+				}
+				inflict_pct = 0;
+			}
+		}
+	};
+
 	// Conditions caused / healed by weapon.
 	if (source.GetType() == Game_Battler::Type_Ally) {
 		auto& ally = static_cast<Game_Actor&>(source);
@@ -708,46 +729,12 @@ bool Game_BattleAlgorithm::Normal::vExecute() {
 			}
 		} else {
 			lcf::rpg::Actor* allydata = lcf::ReaderUtil::GetElement(lcf::Data::actors, ally.GetId());
-			int num_states = allydata->easyrpg_unarmed_state_set.size();
-			for (int i = 0; i < num_states; ++i) {
-				int inflict_pct = 0;
-				if (i < static_cast<int>(allydata->easyrpg_unarmed_state_set.size()) && allydata->easyrpg_unarmed_state_set[i]) {
-					inflict_pct = static_cast<int>(allydata->easyrpg_unarmed_state_chance);
-				}
-				auto state_id = (i + 1);
-
-				if (inflict_pct > 0) {
-					inflict_pct = inflict_pct * target.GetStateProbability(state_id) / 100;
-					if (Rand::PercentChance(inflict_pct)) {
-						if (!State::Has(state_id, target_states) && State::Add(state_id, target_states, target_perm_states, true)) {
-							AddAffectedState(StateEffect{state_id, StateEffect::Inflicted});
-						}
-					}
-					inflict_pct = 0;
-				}
-			}
+			easyrpg_state_set(allydata->easyrpg_unarmed_state_set, allydata->easyrpg_unarmed_state_chance);
 		}
 	} else if (source.GetType() == Game_Battler::Type_Enemy) {
 		auto& enemy = static_cast<Game_Enemy&>(source);
 		lcf::rpg::Enemy* enemydata = lcf::ReaderUtil::GetElement(lcf::Data::enemies, enemy.GetId());
-		int num_states = enemydata->easyrpg_state_set.size();
-		for (int i = 0; i < num_states; ++i) {
-			int inflict_pct = 0;
-			if (i < static_cast<int>(enemydata->easyrpg_state_set.size()) && enemydata->easyrpg_state_set[i]) {
-				inflict_pct = static_cast<int>(enemydata->easyrpg_state_chance);
-			}
-			auto state_id = (i + 1);
-
-			if (inflict_pct > 0) {
-				inflict_pct = inflict_pct * target.GetStateProbability(state_id) / 100;
-				if (Rand::PercentChance(inflict_pct)) {
-					if (!State::Has(state_id, target_states) && State::Add(state_id, target_states, target_perm_states, true)) {
-						AddAffectedState(StateEffect{state_id, StateEffect::Inflicted});
-					}
-				}
-				inflict_pct = 0;
-			}
-		}
+		easyrpg_state_set(enemydata->easyrpg_state_set, enemydata->easyrpg_state_chance);
 	}
 
 	return SetIsSuccess();
-- 
2.33.0
```

**Comment by Ghabry** [comment]
Please also move "Skills: Affected by row modifiers" in a new PR.
This is a complex change with high risk of breakage.

When this is out and you applied your proposed changes we are actually ready to merge this one. :+1: 

------

Do you have any more features in your backlog?

**Comment by rueter37** [comment]
Did the requested changes now. At the moment I haven't got any more features.

**Review by fdelapena — APPROVED** [review]

**Comment by rueter37** [comment]
I'm going to add a PR for "Skills: Affected by row modifiers" as soon as this PR is merged in. Otherwise it is too much of a rebase hell.

**Comment by Ghabry** [comment]
Jenkins: Test this please

**Comment by Ghabry** [comment]
Uhm how do I rerun pipelines?

**Comment by Ghabry** [comment]
@rueter37 pls do a force push here. Is the easiest way to retrigger this ^^

**Comment by Ghabry** [comment]
jenkins: test this please

**Review by Ghabry — APPROVED** [review]

**Pull request merged**
