### PR TITLE
Emscripten related fixes

### PR DESCRIPTION
**Pull request by Ghabry**
Luckily this was debuggable without using Emscripten :D

The first commit fixes e.g. a folder called "music" not being found when launching directly from the game dir. So this was not found by our Android users just because the project-path there is a path with one directory component in it.

-------

The 3rd commit is not an emscripten fix but it resolves an assert on Linux

### CODE REVIEW

**Comment by Ghabry** [comment]
Can also confirm that the # works btw. Though this was already resolved by a different commit.

Works for me

Screenshot_20211116_232827-fs8

**Review by fdelapena — APPROVED** [review]

**Comment by fdelapena** [comment]
Not sure if worth to include a quick one to prevent the "Save" issue like this:

https://easyrpg.org/play/pr2696/?game=thisgamedoesnotexist

**Review by fdelapena — APPROVED** [review]

**Comment by Ghabry** [comment]
This PR is kinda battle tested as it is part of Yume2kki Multi**P**layer since a week :D

**Review by carstene1ns — APPROVED** [review]
Looks good to me.

**Pull request merged**
