### PR TITLE
Battle: Absorb only HP if the target gets killed by the absorption

### PR DESCRIPTION
**Pull request by rueter37**
If a target gets killed by an absorption skill, then only the HP are absorbed.

### CODE REVIEW

**Review by fmatthew5876 — APPROVED** [review]

**Comment by Ghabry** [comment]
Slowly this should be refactored..... except for the stat type this is 4 times the same code which becomes more complex with each PR.

**Comment by fmatthew5876** [comment]
> Slowly this should be refactored..... except for the stat type this is 4 times the same code which becomes more complex with each PR.

It's coming in my next PR, don't worry :)

**Comment by fmatthew5876** [comment]
@rueter37 Are you certain that absorption even works at all for atk, def, spi, and agi?

I'm looking at RE and I don't see this at all. I only see absorb logic for HP and SP.

I checked both dynrpg and 2k3e.

**Comment by fmatthew5876** [comment]
Ok I just tested this myself. 

1. Attack enemy ~ 260 dmg
2. Use a skill which absorbs 9999 atk
3. Attack enemy ~ 260 dmg
4. Use skill on self which raises atk by 9999
5. Attack enemy ~ 750 dmg

So clearly absorb does not work for parameters outside of hp and sp
I used a skill which absorbs 9999 atk.

**Comment by rueter37** [comment]
Did some retests and confirmed you are right. Attack, defense, spirit and agility really cannot be absorbed even in RPG Maker 2003. I have updated this PR.

**Review by fmatthew5876 — APPROVED** [review]

**Pull request merged**
