### PR TITLE
Update key descwiptions

### PR DESCRIPTION
**Pull request by MikuChan03**
Hi~~

Watakushi (said when sewious), doesn't want to be a bothew,
but watakushi believes that the wwong key descwiptions could make usews dizzy.

screenshot_1

So hewe's a tiny PW that changes what I said in #3104. While at it, we also wemove the x3 and x10
pawt in the fast fowward descwiptions, because that's configuwable now

### CODE REVIEW

**Comment by jetrotal** [comment]
Heyo! 

Maybe renaming FF buttons to
"Fast Foward A" and "Fast Foward B" could help, since nowdays it's possible to make the second slower than the first.

Not necessary, but I wonder if it would be possible to concat the speed value from the FF variables to help showing what they do?

Thanks again!

**Comment by MikuChan03** [comment]
@jetrotal sure, will do ^.^
Though if we weally wanted to go all out, we would make the cweation of these
speed modifiews and the keybindings of them dynamic, meaning the usew could have
like 10 diffewent speed modifiews?

**Comment by jetrotal** [comment]
hm... unlimited speed modifiers? I wonder...

Though, there are games that uses a lot of buttons already, and we plan to reserve more shortcuts to when we add support do multiplayer from https://github.com/monokotech/EasyRPG-Multiplayer-Native

Maybe 2 is already a good amount 🤔

**Comment by Mimigris** [comment]
If you want my opinion, 2 buttons to edit the speed is likely good enough for now, it could still be changed later in any case if there's a request. 👍

**Comment by MikuChan03** [comment]
KK,

watashi did all that good stuff! Meaning watashi changed not only the usew facing descwiptions of fast forward,
but also the source code. Only the actual Enums wewe too scawy fow watashi, because they awe being used in platfowms
as well.

screenshot_0

Made it so that the descwiption is dynamically updated too:

screenshot_1

Everything is happening so much 🤪

**Comment by jetrotal** [comment]
Thanks for the help, very sugoi and very kakkoii.

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by MikuChan03** [comment]
Sorry, forgot to exchange a variable name in platforms. Will do so right away.

**Comment by MikuChan03** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
Jenkins: test this please

Sowwy, only admins can do this

**Comment by Ghabry** [comment]
Imo this looks fine. I just want to do a chance on the Android Java Ui side so it reads/writes the value directly through the INI like we already do for some other settings.

Will do this next week, I don't have all the Android dev env crap setup on this system.

**Review by fdelapena — APPROVED** [review]

**Comment by Ghabry** [comment]
Currently not motivated to do the Android stuff. Merging this for now and fixing that minor problem later

**Comment by TruncatedDinoSour** [comment]
a

**Comment by DeveloLongScript** [comment]
github in a nutshell

**trolls**

**Pull request merged**
