### PR TITLE
WIP - Add support to variables in both CommandPlayBGM and CommandPlaySound

### PR DESCRIPTION
**Pull request by jetrotal**
Ok, I followed @Ghabry's suggestions and tried to implement a function to format the sound Effects and Music whenever any of those has variables attached to their parametters.

I'm stuck in 2 problems right now, 1st one:

There's a huge delay between times where the same SFX is played. It does not happens in Maniacs RPG_RT.exe. Is there a rule that waits finishing a sfx before playing it again?

2nd Problem: 

Weird Edge Case.
the hard-coded version of my code works out of the box:

```cpp
bool Game_Interpreter::CommandPlaySound(lcf::rpg::EventCommand const& com) { // code 11550

	std::array<int, 3> params = { com.parameters[0], com.parameters[1], com.parameters[2] };

	if (Player::IsPatchManiac() && com.parameters.size()>3)
	{
		params[0] = ValueOrVariable((com.parameters[3] & 0xF0) >> 4, com.parameters[0]);
		params[1] = ValueOrVariable((com.parameters[3] & 0xF00) >> 8, com.parameters[1]);
		params[2] = ValueOrVariable((com.parameters[3] & 0xF000) >> 12, com.parameters[2]);
	};

	lcf::rpg::Sound sound;
	sound.name = ToString(com.string);
	sound.volume = params[0];
	sound.tempo = params[1];
	sound.balance = params[2];
	Main_Data::game_system->SePlay(sound, true);
	return true;
}
```

But the function version presented in this PR does not work as intended in some cases.

Here's the game I'm using to test it:
https://github.com/EasyRPG/liblcf/files/10188776/Project2.zip

the pitch shift work in most of the sound effects. But if I hold enter and there's a pitch shift in aaa.wav, It gives a very low value, near to zero.

Again, that's does not happens on the hardcoded snippet I wrote before.

Anyone can help me with those issues?

### CODE REVIEW

**Comment by Ghabry** [comment]
Thanks for the PR. I take a look when Xmas is over ;).
What kind of tool are you using? That .gitignore edit is awful 😆

**Comment by jetrotal** [comment]
goddamn it

I'm using gh desktop, it was willing to upload the entire vcpkg folder, and I asked to ignore those files, bloating gitignore.

I marked it to not upadate the gitgnore file, but it went up anyway

**Comment by Ghabry** [comment]
Honestly I would prefer to keep this simple. This needs a bit more code but gives more flexibility.

One problem with your template function is that it starts with a mask of ``0xF`` but the correct code starts with ``0xF0``. The ``0xF`` is for the text arg but this is an assumption that is likely not true everywhere making the API of the function more complex to handle all these edge cases.

Instead I suggest a new ``ValueOrVariableBitfield`` which works almost like ``ValueOrVariable`` but accepts an additional ``shift`` that defines this "4 bit shift" Maniac uses alot.

Then the final code for e.g. SE would be:

```cpp
	lcf::rpg::Sound sound;
	sound.name = ToString(com.string);

	if (Player::IsPatchManiac() && com.parameters.size() >= 4) {
		int mode = com.parameters[3];
		sound.volume = ValueOrVariableBitfield(mode, 1, com.parameters[0]);
		sound.tempo = ValueOrVariableBitfield(mode, 2, com.parameters[1]);
		sound.balance = ValueOrVariableBitfield(mode, 3, com.parameters[2]);
	} else {
		sound.volume = com.parameters[0];
		sound.tempo = com.parameters[1];
		sound.balance = com.parameters[2];
	}

	Main_Data::game_system->SePlay(sound, true);
	return true;
```

Complete patch:

```diff
diff --git a/.gitignore b/.gitignore
index fe5f79843..83a7e2b74 100644
--- a/.gitignore
+++ b/.gitignore
@@ -61,6 +61,8 @@ install_manifest.txt
 *.ilk
 *.pdb
 /resources/player.rc
+.vs/
+vcpkg/
 
 # ninja
 .ninja_*
diff --git a/src/game_interpreter.cpp b/src/game_interpreter.cpp
index 8e95d804e..3aa3d09ce 100644
--- a/src/game_interpreter.cpp
+++ b/src/game_interpreter.cpp
@@ -1733,6 +1733,10 @@ int Game_Interpreter::ValueOrVariable(int mode, int val) {
 	return -1;
 }
 
+int Game_Interpreter::ValueOrVariableBitfield(int mode, int shift, int val) {
+	return ValueOrVariable((mode & (0xF << shift * 4)) >> shift * 4, val);
+}
+
 bool Game_Interpreter::CommandChangeParameters(lcf::rpg::EventCommand const& com) { // Code 10430
 	int value = OperateValue(
 		com.parameters[2],
@@ -1987,10 +1991,20 @@ bool Game_Interpreter::CommandWait(lcf::rpg::EventCommand const& com) { // code
 bool Game_Interpreter::CommandPlayBGM(lcf::rpg::EventCommand const& com) { // code 11510
 	lcf::rpg::Music music;
 	music.name = ToString(com.string);
-	music.fadein = com.parameters[0];
-	music.volume = com.parameters[1];
-	music.tempo = com.parameters[2];
-	music.balance = com.parameters[3];
+
+	if (Player::IsPatchManiac() && com.parameters.size() >= 5) {
+		int mode = com.parameters[4];
+		music.fadein = ValueOrVariableBitfield(mode, 1, com.parameters[0]);
+		music.volume = ValueOrVariableBitfield(mode, 2, com.parameters[1]);
+		music.tempo = ValueOrVariableBitfield(mode, 3, com.parameters[2]);
+		music.balance = ValueOrVariableBitfield(mode, 4, com.parameters[3]);
+	} else {
+		music.fadein = com.parameters[0];
+		music.volume = com.parameters[1];
+		music.tempo = com.parameters[2];
+		music.balance = com.parameters[3];
+	}
+
 	Main_Data::game_system->BgmPlay(music);
 	return true;
 }
@@ -2004,9 +2018,18 @@ bool Game_Interpreter::CommandFadeOutBGM(lcf::rpg::EventCommand const& com) { //
 bool Game_Interpreter::CommandPlaySound(lcf::rpg::EventCommand const& com) { // code 11550
 	lcf::rpg::Sound sound;
 	sound.name = ToString(com.string);
-	sound.volume = com.parameters[0];
-	sound.tempo = com.parameters[1];
-	sound.balance = com.parameters[2];
+
+	if (Player::IsPatchManiac() && com.parameters.size() >= 4) {
+		int mode = com.parameters[3];
+		sound.volume = ValueOrVariableBitfield(mode, 1, com.parameters[0]);
+		sound.tempo = ValueOrVariableBitfield(mode, 2, com.parameters[1]);
+		sound.balance = ValueOrVariableBitfield(mode, 3, com.parameters[2]);
+	} else {
+		sound.volume = com.parameters[0];
+		sound.tempo = com.parameters[1];
+		sound.balance = com.parameters[2];
+	}
+
 	Main_Data::game_system->SePlay(sound, true);
 	return true;
 }
diff --git a/src/game_interpreter.h b/src/game_interpreter.h
index 72db2127c..42d07eaec 100644
--- a/src/game_interpreter.h
+++ b/src/game_interpreter.h
@@ -162,6 +162,7 @@ protected:
 	 */
 	static std::vector<Game_Actor*> GetActors(int mode, int id);
 	static int ValueOrVariable(int mode, int val);
+	static int ValueOrVariableBitfield(int mode, int shift, int val);
 
 	/**
 	 * When current frame finishes executing we pop the stack
-- 
2.38.0
```

**Comment by Ghabry** [comment]
replaced by #2914

**Pull request closed without merging**
