### PR TITLE
Android: Fix Drawer rendering error in the PlayerActivity and minor UX improvements

### LINKED ISSUE #1012: Android: Collection of rendering errors in the EasyRPGActivity
First candidate is a japanese guy on an Xperia with Android 6

In portrait mode a part of the screen is white.

screenshot_20160828-094853

### PR DESCRIPTION
**Pull request by Ghabry**
At least on my Android 4.0.3 :+1: 

Minor UX improvement: Edit layout while ingame :o

Fixes #1012.

### CODE REVIEW

**Comment by BlisterB** [comment]
Wow I did serious research but never find that one!

**Comment by BlisterB** [comment]
I've tested : it fixes the problem I reported in my PR (the y alignement in portrait mode). 👍

**Comment by Ghabry** [comment]
I'm finished messing with BlisterBoys masterpiece 😂

**Comment by BlisterB** [comment]
Ghabry, this is a nice functionality but I don't think Android will allow you to do this x))).
It will likely reload the EasyRPG Player Activity from scratch after some return on this Activity. Mean reload from the title screen.

**Comment by Ghabry** [comment]
BlisterB, I tested it and at least on my devices it works. But you are right, there is a risk of the Activity restarting... :D but the same risk is when suspending.

Btw @BlisterB  I noticed something strange: When suspending the app and resuming the framerate of the Player the framerate on my phone reduces to 30 FPS... But hiding the layout fixes it... Android is stupid.

**Comment by Ghabry** [comment]
Updated some strings and shortened the instructions because nobody read the button part anyway ^^'

**Comment by carstene1ns** [comment]
jenkins: test this please <3

**Comment by BlisterB** [comment]
@Ghabry There is some way to ask to Android to not kill an app, but I think this would be better with a function pausing the game.
Is there a way to have a native function that can pause the game, and another to mute/unmute the audio?
That would be could to call them from the Player Activity in a middle of a game.

**Comment by Ghabry** [comment]
Uhm the game is already paused because it recives a focus lost event.

**Comment by BlisterB** [comment]
For mute the audio : it would be nice to modify this option in game.
For pausing the game : for example, if you open the menu, the game is not paused (it's problematic on some circumstances).

(sorry for the wrong topic, pretty headache this night ._.)

**Comment by Ghabry** [comment]
There are actually "Player::Pause" and "Player::Resume" but they don't really Pause the execution, only the background music...

Concerning Global Audio for BGM and SEs: This doesn't exist at all for the Player. If you want this: Add new functions to the audio interface and call them. Sorry, find someone who knows a bit of C++.

**Comment by BlisterB** [comment]
lol no problem, it's not important at all.
I did a lot of C in a period, but I won't anymore I think :p.

Thanks for the Player's function information, I actually could use it to pause BGM. But people would  complain that it doesn't stop all the sound x).

**Comment by Ghabry** [comment]
Crash reported on Android

```
java.lang.NullPointerException
	at org.easyrpg.player.settings.SettingsManager.setGameFolderList(SettingsManager.java:120)
	at org.easyrpg.player.settings.SettingsManager.addGameDirectory(SettingsManager.java:105)
	at org.easyrpg.player.settings.SettingsGamesFoldersActivity$2.run(SettingsGamesFoldersActivity.java:84)
	at org.easyrpg.player.DirectoryChooser$1$1.onClick(DirectoryChooser.java:67)
	at android.view.View.performClick(View.java:4204)
	at android.view.View$PerformClick.run(View.java:17393)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5117)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:954)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:721)
	at dalvik.system.NativeStart.main(Native Method)
```

I had this also once. Happens when the game directory list is empty. No idea how this happens, usually restarting the app fixed it *shrug*

**Comment by BlisterB** [comment]
Okay, I'll open an issue ticket and solve it this week-end. (I think you can merge this PR, work like a charm)

**Pull request merged**
